//---------- AFR ----------
const adventureForgottenRealms_page1 = [
    {
        name: "Aberrant Mind Sorcerer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527331&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Acererak the Archlich",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527374&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Adult Gold Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527503&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Air-Cult Elemental",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527332&type=card",
        cmc: "6",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Arborea Pegasus",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527289&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Arcane Investigator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527333&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Armory Veteran",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527417&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Asmodeus the Archfiend",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527375&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Bag of Holding",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527527&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Baleful Beholder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527376&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Bar the Gate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527334&type=card",
        cmc: "3",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Barbarian Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527418&type=card",
        cmc: "1",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Bard Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527504&type=card",
        cmc: "2",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Barrowin of Clan Undurr",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527505&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Battle Cry Goblin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527419&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Black Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527377&type=card",
        cmc: "7",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Blink Dog",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527290&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Blue Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527336&type=card",
        cmc: "7",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Boots of Speed",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527420&type=card",
        cmc: "1",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Brazen Dwarf",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527421&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Bruenor Battlehammer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527506&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Bulette",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527460&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Bull's Strength",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527461&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Burning Hands",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527422&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Cave of the Frost Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527540&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Celestial Unicorn",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527292&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Chaos Channeler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527423&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Charmed Sleep",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527337&type=card",
        cmc: "3",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Check for Traps",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527379&type=card",
        cmc: "2",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Choose Your Weapon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527462&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Circle of Dreams Druid",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527463&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Circle of the Moon Druid",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527464&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Clattering Skeletons",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527380&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Cleric Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527293&type=card",
        cmc: "1",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Clever Conjurer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527338&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Cloister Gargoyle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527294&type=card",
        cmc: "3",
        color: "White",
        type: "Artifact",
    },
    {
        name: "Compelled Duel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527465&type=card",
        cmc: "2",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Contact Other Plane",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527339&type=card",
        cmc: "4",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Critical Hit",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527424&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Dancing Sword",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527295&type=card",
        cmc: "2",
        color: "White",
        type: "Artifact",
    },
    {
        name: "Dawnbringer Cleric",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527296&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Deadly Dispute",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527381&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Death-Priest of Myrkul",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527382&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Delina, Wild Mage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527425&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Delver's Torch",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527297&type=card",
        cmc: "2",
        color: "White",
        type: "Artifact",
    },
    {
        name: "Demilich",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527340&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Demogorgon's Clutches",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527383&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Den of the Bugbear",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527541&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Devoted Paladin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527298&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Devour Intellect",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527384&type=card",
        cmc: "1",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Dire Wolf Prowler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527466&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Displacer Beast",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527341&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Divine Smite",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527299&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Djinni Windseer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527342&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Dragon Turtle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527343&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Dragon's Disciple",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527300&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Dragon's Fire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527426&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Drider",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527385&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Drizzt Do'Urden",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527507&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Druid Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527467&type=card",
        cmc: "2",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Dueling Rapier",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527427&type=card",
        cmc: "1",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Dungeon Crawler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527386&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Dungeon Descent",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527542&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Dungeon Map",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527529&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Dungeon of the Mad Mage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=530447&type=card",
        cmc: "0",
        color: undefined,
        type: undefined,
    },
    {
        name: "Dwarfhold Champion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527301&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Earth-Cult Elemental",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527428&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Ebondeath, Dracolich",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527387&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Eccentric Apprentice",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527344&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Ellywick Tumblestrum",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527468&type=card",
        cmc: "4",
        color: "Green",
        type: "Planeswalker",
    },
    {
        name: "Elturgard Ranger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527469&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Evolving Wilds",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527543&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Eye of Vecna",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527530&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Eyes of the Beholder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527388&type=card",
        cmc: "6",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Farideh, Devil's Chosen",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527508&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Farideh's Fireball",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527429&type=card",
        cmc: "5",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Fates' Reversal",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527389&type=card",
        cmc: "2",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Feign Death",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527390&type=card",
        cmc: "1",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Feywild Trickster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527345&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Fifty Feet of Rope",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527531&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Fighter Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527509&type=card",
        cmc: "2",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Find the Path",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527470&type=card",
        cmc: "3",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Flameskull",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527430&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Flumph",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527302&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Fly",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527346&type=card",
        cmc: "1",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Forest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=530172&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Forsworn Paladin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527391&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Froghemoth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527471&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Gelatinous Cube",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527392&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Gloom Stalker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527303&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Gnoll Hunter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527472&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Goblin Javelineer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527431&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Goblin Morningstar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527432&type=card",
        cmc: "2",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Grand Master of Flowers",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527304&type=card",
        cmc: "4",
        color: "White",
        type: "Planeswalker",
    },
    {
        name: "Grazilaxx, Illithid Scholar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527347&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Greataxe",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527532&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Green Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527473&type=card",
        cmc: "6",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Gretchen Titchwillow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527510&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Grim Bounty",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527393&type=card",
        cmc: "4",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Grim Wanderer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527394&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
];

const adventureForgottenRealms_page2 = [
    {
        name: "Guardian of Faith",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527305&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Guild Thief",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527348&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Half-Elf Monk",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527306&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Hall of Storm Giants",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527544&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Hama Pashar, Ruin Seeker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527511&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Hand of Vecna",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527533&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Herald of Hadar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527395&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Hill Giant Herdgorger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527474&type=card",
        cmc: "6",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Hired Hexblade",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527396&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Hive of the Eye Tyrant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527545&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Hoard Robber",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527397&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Hoarding Ogre",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527433&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Hobgoblin Bandit Lord",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527434&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Hobgoblin Captain",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527435&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Hulking Bugbear",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527436&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Hunter's Mark",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527475&type=card",
        cmc: "4",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Icingdeath, Frost Tyrant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527307&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Improvised Weaponry",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527437&type=card",
        cmc: "3",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Inferno of the Star Mounts",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527438&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Ingenious Smith",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527308&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Inspiring Bard",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527476&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Instrument of the Bards",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527477&type=card",
        cmc: "1",
        color: "Green",
        type: "Artifact",
    },
    {
        name: "Intrepid Outlander",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527478&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Iron Golem",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527534&type=card",
        cmc: "4",
        color: "4",
        type: "Artifact",
    },
    {
        name: "Island",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=530160&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Iymrith, Desert Doom",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527349&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Jaded Sell-Sword",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527439&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Kalain, Reclusive Painter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527512&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Keen-Eared Sentry",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527309&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Kick in the Door",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527440&type=card",
        cmc: "1",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Krydle of Baldur's Gate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527513&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Lair of the Hydra",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527546&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Leather Armor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527535&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Lightfoot Rogue",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527398&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Loathsome Troll",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527479&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Lolth, Spider Queen",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527399&type=card",
        cmc: "5",
        color: "Black",
        type: "Planeswalker",
    },
    {
        name: "Long Rest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527480&type=card",
        cmc: "3",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Lost Mine of Phandelver",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=530448&type=card",
        cmc: "0",
        color: undefined,
        type: undefined,
    },
    {
        name: "Loyal Warhound",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527310&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Lurking Roper",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527481&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Magic Missile",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527441&type=card",
        cmc: "3",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Manticore",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527400&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Meteor Swarm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527442&type=card",
        cmc: "3",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Mimic",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527536&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Mind Flayer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527350&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Minimus Containment",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527311&type=card",
        cmc: "3",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Minion of the Mighty",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527443&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Minsc, Beloved Ranger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527514&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Monk Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527515&type=card",
        cmc: "2",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Monk of the Open Hand",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527312&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Moon-Blessed Cleric",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527313&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Mordenkainen",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527351&type=card",
        cmc: "6",
        color: "Blue",
        type: "Planeswalker",
    },
    {
        name: "Mordenkainen's Polymorph",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527352&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Mountain",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=530168&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Nadaar, Selfless Paladin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527314&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Neverwinter Dryad",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527482&type=card",
        cmc: "1",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Ochre Jelly",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527483&type=card",
        cmc: "1",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Old Gnawbone",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527484&type=card",
        cmc: "7",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Orb of Dragonkind",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527444&type=card",
        cmc: "2",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Orcus, Prince of Undeath",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527516&type=card",
        cmc: "4",
        color: "2",
        type: "Creature",
    },
    {
        name: "Oswald Fiddlebender",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527315&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Owlbear",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527485&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Paladin Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527316&type=card",
        cmc: "1",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Paladin's Shield",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527317&type=card",
        cmc: "2",
        color: "White",
        type: "Artifact",
    },
    {
        name: "Pixie Guide",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527353&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Plains",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=530156&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Planar Ally",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527318&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Plate Armor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527319&type=card",
        cmc: "3",
        color: "White",
        type: "Artifact",
    },
    {
        name: "Plummet",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527486&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Plundering Barbarian",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527445&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Portable Hole",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527320&type=card",
        cmc: "1",
        color: "White",
        type: "Artifact",
    },
    {
        name: "Potion of Healing",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527321&type=card",
        cmc: "2",
        color: "White",
        type: "Artifact",
    },
    {
        name: "Power of Persuasion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527354&type=card",
        cmc: "3",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Power Word Kill",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527401&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Precipitous Drop",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527402&type=card",
        cmc: "3",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Price of Loyalty",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527446&type=card",
        cmc: "3",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Priest of Ancient Lore",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527322&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Prosperous Innkeeper",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527487&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Purple Worm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527488&type=card",
        cmc: "7",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Rally Maneuver",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527323&type=card",
        cmc: "3",
        color: "White",
        type: "Instant",
    },
    {
        name: "Ranger Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527489&type=card",
        cmc: "2",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Ranger's Hawk",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527324&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Ranger's Longbow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527490&type=card",
        cmc: "2",
        color: "Green",
        type: "Artifact",
    },
    {
        name: "Ray of Enfeeblement",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527403&type=card",
        cmc: "1",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Ray of Frost",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527355&type=card",
        cmc: "2",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Reaper's Talisman",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527404&type=card",
        cmc: "1",
        color: "Black",
        type: "Artifact",
    },
    {
        name: "Red Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527447&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Rimeshield Frost Giant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527356&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Rogue Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527517&type=card",
        cmc: "2",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Rust Monster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527448&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Scaled Herbalist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527491&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Scion of Stygia",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527357&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Secret Door",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527358&type=card",
        cmc: "1",
        color: "Blue",
        type: "Artifact",
    },
    {
        name: "Sepulcher Ghoul",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527405&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Shambling Ghast",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527406&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Shessra, Death's Whisper",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527518&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Shocking Grasp",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527359&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Shortcut Seeker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527360&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Silver Raven",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527361&type=card",
        cmc: "1",
        color: "Blue",
        type: "Artifact",
    },
    {
        name: "Skeletal Swarming",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527519&type=card",
        cmc: "5",
        color: "Black",
        type: "Enchantment",
    },
];

const adventureForgottenRealms_page3 = [
    {
        name: "Skullport Merchant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527407&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Sorcerer Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527520&type=card",
        cmc: "2",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Soulknife Spy",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527362&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Spare Dagger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527537&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Sphere of Annihilation",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527408&type=card",
        cmc: "1",
        color: "Black",
        type: "Artifact",
    },
    {
        name: "Spiked Pit Trap",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527538&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Split the Party",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527363&type=card",
        cmc: "5",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Spoils of the Hunt",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527492&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Steadfast Paladin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527325&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Sudden Insight",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527364&type=card",
        cmc: "6",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Swamp",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=530164&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Swarming Goblins",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527449&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Sylvan Shepherd",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527493&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Targ Nar, Demon-Fang Gnoll",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527521&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Tasha's Hideous Laughter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527365&type=card",
        cmc: "3",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Teleportation Circle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527326&type=card",
        cmc: "4",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Temple of the Dragon Queen",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527547&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "The Blackstaff of Waterdeep",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527335&type=card",
        cmc: "1",
        color: "Blue",
        type: "Artifact",
    },
    {
        name: "The Book of Exalted Deeds",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527291&type=card",
        cmc: "3",
        color: "White",
        type: "Artifact",
    },
    {
        name: "The Book of Vile Darkness",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527378&type=card",
        cmc: "3",
        color: "Black",
        type: "Artifact",
    },
    {
        name: "The Deck of Many Things",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527528&type=card",
        cmc: "5",
        color: "5",
        type: "Artifact",
    },
    {
        name: "The Tarrasque",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527494&type=card",
        cmc: "9",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Thieves' Tools",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527409&type=card",
        cmc: "2",
        color: "Black",
        type: "Artifact",
    },
    {
        name: "Tiamat",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527522&type=card",
        cmc: "7",
        color: "White",
        type: "Creature",
    },
    {
        name: "Tiger-Tribe Hunter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527450&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Tomb of Annihilation",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=530449&type=card",
        cmc: "0",
        color: undefined,
        type: undefined,
    },
    {
        name: "Treasure Chest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527539&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Treasure Vault",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527548&type=card",
        cmc: "0",
        color: undefined,
        type: "Artifact",
    },
    {
        name: "Trelasarra, Moon Dancer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527523&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Trickster's Talisman",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527366&type=card",
        cmc: "1",
        color: "Blue",
        type: "Artifact",
    },
    {
        name: "Triumphant Adventurer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527524&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "True Polymorph",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527367&type=card",
        cmc: "6",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Underdark Basilisk",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527495&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Unexpected Windfall",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527451&type=card",
        cmc: "4",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Valor Singer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527452&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Vampire Spawn",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527410&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Varis, Silverymoon Ranger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527496&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Veteran Dungeoneer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527327&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Volo, Guide to Monsters",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527525&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Vorpal Sword",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527411&type=card",
        cmc: "1",
        color: "Black",
        type: "Artifact",
    },
    {
        name: "Wandering Troubadour",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527497&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Warlock Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527412&type=card",
        cmc: "1",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Werewolf Pack Leader",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527498&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Westgate Regent",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527413&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "White Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527328&type=card",
        cmc: "6",
        color: "White",
        type: "Creature",
    },
    {
        name: "Wight",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527414&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Wild Shape",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527499&type=card",
        cmc: "1",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Wish",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527453&type=card",
        cmc: "3",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Wizard Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527368&type=card",
        cmc: "1",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Wizard's Spellbook",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527369&type=card",
        cmc: "7",
        color: "Blue",
        type: "Artifact",
    },
    {
        name: "Xanathar, Guild Kingpin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527526&type=card",
        cmc: "6",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Xorn",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527454&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "You Come to a River",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527370&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "You Come to the Gnoll Camp",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527455&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "You Find a Cursed Idol",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527500&type=card",
        cmc: "2",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "You Find Some Prisoners",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527456&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "You Find the Villains' Lair",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527371&type=card",
        cmc: "3",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "You Happen On a Glade",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527501&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "You Hear Something on Watch",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527329&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "You Meet in a Tavern",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527502&type=card",
        cmc: "4",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "You See a Guard Approach",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527372&type=card",
        cmc: "1",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "You See a Pair of Goblins",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527457&type=card",
        cmc: "3",
        color: "Red",
        type: "Instant",
    },
    {
        name: "You're Ambushed on the Road",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527330&type=card",
        cmc: "1",
        color: "White",
        type: "Instant",
    },
    {
        name: "Yuan-Ti Fang-Blade",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527415&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Yuan-Ti Malison",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527373&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Zalto, Fire Giant Duke",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527458&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Zariel, Archduke of Avernus",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527459&type=card",
        cmc: "4",
        color: "Red",
        type: "Planeswalker",
    },
    {
        name: "Zombie Ogre",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527416&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
];

export const adventureForgottenRealms = adventureForgottenRealms_page1.concat(
    adventureForgottenRealms_page2,
    adventureForgottenRealms_page3
);

export const adventureForgottenRealmsObj = adventureForgottenRealms.reduce((acc, card) => {
    return {
        ...acc,
        [card.name]: {
            ["image"]: card.image,
            ["cmc"]: card.cmc,
            ["color"]: card.color,
            ["type"]: card.type,
        },
    };
}, {});
