//---------- AFR ----------
const adventureForgottenRealms_page1 = [
    {
        name: "Aberrant Mind Sorcerer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527331&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Acererak the Archlich",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527374&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Adult Gold Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527503&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Air-Cult Elemental",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527332&type=card",
        cmc: "6",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Arborea Pegasus",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527289&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Arcane Investigator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527333&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Armory Veteran",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527417&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Asmodeus the Archfiend",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527375&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Bag of Holding",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527527&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Baleful Beholder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527376&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Bar the Gate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527334&type=card",
        cmc: "3",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Barbarian Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527418&type=card",
        cmc: "1",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Bard Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527504&type=card",
        cmc: "2",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Barrowin of Clan Undurr",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527505&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Battle Cry Goblin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527419&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Black Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527377&type=card",
        cmc: "7",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Blink Dog",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527290&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Blue Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527336&type=card",
        cmc: "7",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Boots of Speed",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527420&type=card",
        cmc: "1",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Brazen Dwarf",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527421&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Bruenor Battlehammer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527506&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Bulette",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527460&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Bull's Strength",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527461&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Burning Hands",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527422&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Cave of the Frost Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527540&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Celestial Unicorn",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527292&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Chaos Channeler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527423&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Charmed Sleep",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527337&type=card",
        cmc: "3",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Check for Traps",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527379&type=card",
        cmc: "2",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Choose Your Weapon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527462&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Circle of Dreams Druid",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527463&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Circle of the Moon Druid",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527464&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Clattering Skeletons",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527380&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Cleric Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527293&type=card",
        cmc: "1",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Clever Conjurer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527338&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Cloister Gargoyle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527294&type=card",
        cmc: "3",
        color: "White",
        type: "Artifact",
    },
    {
        name: "Compelled Duel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527465&type=card",
        cmc: "2",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Contact Other Plane",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527339&type=card",
        cmc: "4",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Critical Hit",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527424&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Dancing Sword",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527295&type=card",
        cmc: "2",
        color: "White",
        type: "Artifact",
    },
    {
        name: "Dawnbringer Cleric",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527296&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Deadly Dispute",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527381&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Death-Priest of Myrkul",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527382&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Delina, Wild Mage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527425&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Delver's Torch",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527297&type=card",
        cmc: "2",
        color: "White",
        type: "Artifact",
    },
    {
        name: "Demilich",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527340&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Demogorgon's Clutches",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527383&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Den of the Bugbear",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527541&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Devoted Paladin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527298&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Devour Intellect",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527384&type=card",
        cmc: "1",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Dire Wolf Prowler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527466&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Displacer Beast",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527341&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Divine Smite",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527299&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Djinni Windseer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527342&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Dragon Turtle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527343&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Dragon's Disciple",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527300&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Dragon's Fire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527426&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Drider",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527385&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Drizzt Do'Urden",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527507&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Druid Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527467&type=card",
        cmc: "2",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Dueling Rapier",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527427&type=card",
        cmc: "1",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Dungeon Crawler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527386&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Dungeon Descent",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527542&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Dungeon Map",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527529&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Dungeon of the Mad Mage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=530447&type=card",
        cmc: "0",
        color: undefined,
        type: undefined,
    },
    {
        name: "Dwarfhold Champion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527301&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Earth-Cult Elemental",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527428&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Ebondeath, Dracolich",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527387&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Eccentric Apprentice",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527344&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Ellywick Tumblestrum",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527468&type=card",
        cmc: "4",
        color: "Green",
        type: "Planeswalker",
    },
    {
        name: "Elturgard Ranger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527469&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Evolving Wilds",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527543&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Eye of Vecna",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527530&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Eyes of the Beholder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527388&type=card",
        cmc: "6",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Farideh, Devil's Chosen",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527508&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Farideh's Fireball",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527429&type=card",
        cmc: "5",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Fates' Reversal",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527389&type=card",
        cmc: "2",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Feign Death",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527390&type=card",
        cmc: "1",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Feywild Trickster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527345&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Fifty Feet of Rope",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527531&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Fighter Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527509&type=card",
        cmc: "2",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Find the Path",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527470&type=card",
        cmc: "3",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Flameskull",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527430&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Flumph",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527302&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Fly",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527346&type=card",
        cmc: "1",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Forest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=530172&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Forsworn Paladin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527391&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Froghemoth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527471&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Gelatinous Cube",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527392&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Gloom Stalker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527303&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Gnoll Hunter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527472&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Goblin Javelineer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527431&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Goblin Morningstar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527432&type=card",
        cmc: "2",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Grand Master of Flowers",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527304&type=card",
        cmc: "4",
        color: "White",
        type: "Planeswalker",
    },
    {
        name: "Grazilaxx, Illithid Scholar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527347&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Greataxe",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527532&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Green Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527473&type=card",
        cmc: "6",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Gretchen Titchwillow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527510&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Grim Bounty",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527393&type=card",
        cmc: "4",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Grim Wanderer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527394&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
];
