//---------- Zendikar Rising ----------
export const ikoria_page1 = [
    {
        name: "Adaptive Shimmerer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479521&type=card",
        cmc: "5",
        color: "5",
        type: "Creature",
    },
    {
        name: "Adventurous Impulse",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479662&type=card",
        cmc: "1",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Aegis Turtle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479559&type=card",
        cmc: "1",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Alert Heedbonder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479738&type=card",
        cmc: "3",
        color: "Green or White",
        type: "Creature",
    },
    {
        name: "Almighty Brushwagg",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479663&type=card",
        cmc: "1",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Anticipate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479560&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Archipelagore",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479561&type=card",
        cmc: "7",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Auspicious Starrix",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479664&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Avian Oddity",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479562&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Back for More",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479697&type=card",
        cmc: "6",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Barrier Breach",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479665&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Bastion of Remembrance",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479593&type=card",
        cmc: "3",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Blade Banish",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479524&type=card",
        cmc: "4",
        color: "White",
        type: "Instant",
    },
    {
        name: "Blazing Volley",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479627&type=card",
        cmc: "1",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Blisterspit Gremlin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479628&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Blitz Leech",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479594&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Blitz of the Thunder-Raptor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479629&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Blood Curdle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479595&type=card",
        cmc: "4",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Bloodfell Caves",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479763&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Blossoming Sands",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479764&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Bonders' Enclave",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479765&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Boneyard Lurker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479698&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Boon of the Wish-Giver",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479563&type=card",
        cmc: "6",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Boot Nipper",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479596&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Bristling Boar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479666&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Brokkos, Apex of Forever",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479699&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Bushmeat Poacher",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479597&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Call of the Death-Dweller",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479598&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Capture Sphere",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479564&type=card",
        cmc: "4",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Cathartic Reunion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479630&type=card",
        cmc: "2",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Cavern Whisperer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479599&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Channeled Force",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479700&type=card",
        cmc: "4",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Charge of the Forever-Beast",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479667&type=card",
        cmc: "3",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Checkpoint Officer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479525&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Chevill, Bane of Monsters",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479701&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Chittering Harvester",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479600&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Clash of Titans",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479631&type=card",
        cmc: "5",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Cloudpiercer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479632&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Colossification",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479668&type=card",
        cmc: "7",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Convolute",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479565&type=card",
        cmc: "3",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Coordinated Charge",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479526&type=card",
        cmc: "5",
        color: "White",
        type: "Instant",
    },
    {
        name: "Corpse Churn",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479601&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Crystacean",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479566&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Crystalline Giant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479754&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Cubwarden",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479527&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Cunning Nightbonder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479739&type=card",
        cmc: "2",
        color: "Blue or Black",
        type: "Creature",
    },
    {
        name: "Dark Bargain",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479602&type=card",
        cmc: "4",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Daysquad Marshal",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479528&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Dead Weight",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479603&type=card",
        cmc: "1",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Death's Oasis",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479702&type=card",
        cmc: "3",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Dire Tactics",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479703&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Dirge Bat",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479604&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Dismal Backwater",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479766&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Divine Arrow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479529&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Drannith Healer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479530&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Drannith Magistrate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479531&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Drannith Stinger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479633&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Dreamtail Heron",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479567&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Durable Coilbug",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479605&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Duskfang Mentor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479606&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Easy Prey",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479607&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Eerie Ultimatum",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479704&type=card",
        cmc: "7",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Emergent Ultimatum",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479705&type=card",
        cmc: "7",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Escape Protocol",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479568&type=card",
        cmc: "2",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Essence Scatter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479569&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Essence Symbiote",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479669&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Everquill Phoenix",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479634&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Evolving Wilds",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479767&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Excavation Mole",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479670&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Extinction Event",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479608&type=card",
        cmc: "4",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Exuberant Wolfbear",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479671&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Facet Reader",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479570&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Farfinder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479522&type=card",
        cmc: "3",
        color: "3",
        type: "Creature",
    },
    {
        name: "Ferocious Tigorilla",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479635&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Fertilid",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479672&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Fiend Artisan",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479740&type=card",
        cmc: "2",
        color: "Black or Green",
        type: "Creature",
    },
    {
        name: "Fight as One",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479532&type=card",
        cmc: "1",
        color: "White",
        type: "Instant",
    },
    {
        name: "Fire Prophecy",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479636&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Flame Spill",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479637&type=card",
        cmc: "3",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Flourishing Fox",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479533&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Flycatcher Giraffid",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479673&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Footfall Crater",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479638&type=card",
        cmc: "1",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Forbidden Friendship",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479639&type=card",
        cmc: "2",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Forest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=482547&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Frenzied Raptor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479640&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Frillscare Mentor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479641&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Frondland Felidar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479706&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Frost Lynx",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479571&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Frostveil Ambush",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479572&type=card",
        cmc: "5",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Fully Grown",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479674&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Garrison Cat",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479534&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Gemrazer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479675&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "General Kudro of Drannith",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479707&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "General's Enforcer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479708&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Genesis Ultimatum",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479709&type=card",
        cmc: "7",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Glimmerbell",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479573&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Gloom Pangolin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479609&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Glowstone Recluse",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479676&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Go for Blood",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479642&type=card",
        cmc: "2",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Greater Sandwurm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479677&type=card",
        cmc: "7",
        color: "Green",
        type: "Creature",
    },
];
const ikoria_page2 = [
    {
        name: "Grimdancer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479610&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Gust of Wind",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479574&type=card",
        cmc: "4",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Gyruda, Doom of Depths",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479741&type=card",
        cmc: "6",
        color: "Blue or Black",
        type: "Creature",
    },
    {
        name: "Hampering Snare",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479575&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Heartless Act",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479611&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Heightened Reflexes",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479643&type=card",
        cmc: "1",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Helica Glider",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479535&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Honey Mammoth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479678&type=card",
        cmc: "6",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Hornbash Mentor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479679&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Humble Naturalist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479680&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Hunted Nightmare",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479612&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Huntmaster Liger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479536&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Illuna, Apex of Wishes",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479710&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Imposing Vantasaur",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479537&type=card",
        cmc: "6",
        color: "White",
        type: "Creature",
    },
    {
        name: "Indatha Crystal",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479755&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Indatha Triome",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479768&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Insatiable Hemophage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479613&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Inspired Ultimatum",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479711&type=card",
        cmc: "7",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Island",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=482538&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Ivy Elemental",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479681&type=card",
        cmc: "1",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Jegantha, the Wellspring",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479742&type=card",
        cmc: "5",
        color: "Red or Green",
        type: "Creature",
    },
    {
        name: "Jubilant Skybonder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479743&type=card",
        cmc: "3",
        color: "White or Blue",
        type: "Creature",
    },
    {
        name: "Jungle Hollow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479769&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Kaheera, the Orphanguard",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479744&type=card",
        cmc: "3",
        color: "Green or White",
        type: "Creature",
    },
    {
        name: "Keensight Mentor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479538&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Keep Safe",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479576&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Keruga, the Macrosage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479745&type=card",
        cmc: "5",
        color: "Green or Blue",
        type: "Creature",
    },
    {
        name: "Ketria Crystal",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479756&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Ketria Triome",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479770&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Kinnan, Bonder Prodigy",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479712&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Kogla, the Titan Ape",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479682&type=card",
        cmc: "6",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Labyrinth Raptor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479713&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Lava Serpent",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479644&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Lavabrink Venturer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479539&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Lead the Stampede",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479683&type=card",
        cmc: "3",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Light of Hope",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479540&type=card",
        cmc: "1",
        color: "White",
        type: "Instant",
    },
    {
        name: "Lore Drakkis",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479714&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Lukka, Coppercoat Outcast",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479645&type=card",
        cmc: "5",
        color: "Red",
        type: "Planeswalker",
    },
    {
        name: "Luminous Broodmoth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479541&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Lurking Deadeye",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479614&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Lurrus of the Dream-Den",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479746&type=card",
        cmc: "3",
        color: "White or Black",
        type: "Creature",
    },
    {
        name: "Lutri, the Spellchaser",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479747&type=card",
        cmc: "3",
        color: "Blue or Red",
        type: "Creature",
    },
    {
        name: "Majestic Auricorn",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479542&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Maned Serval",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479543&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Memory Leak",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479615&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Migration Path",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479684&type=card",
        cmc: "4",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Migratory Greathorn",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479685&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Momentum Rumbler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479646&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Monstrous Step",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479686&type=card",
        cmc: "5",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Mosscoat Goriak",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479687&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Mountain",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=482544&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Mutual Destruction",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479616&type=card",
        cmc: "1",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Mysterious Egg",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479523&type=card",
        cmc: "1",
        color: "1",
        type: "Creature",
    },
    {
        name: "Mystic Subdual",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479577&type=card",
        cmc: "2",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Mythos of Brokkos",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479688&type=card",
        cmc: "4",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Mythos of Illuna",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479578&type=card",
        cmc: "4",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Mythos of Nethroi",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479617&type=card",
        cmc: "3",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Mythos of Snapdax",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479544&type=card",
        cmc: "4",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Mythos of Vadrok",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479647&type=card",
        cmc: "4",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Narset of the Ancient Way",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479715&type=card",
        cmc: "4",
        color: "Blue",
        type: "Planeswalker",
    },
    {
        name: "Necropanther",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479716&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Nethroi, Apex of Death",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479717&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Neutralize",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479579&type=card",
        cmc: "3",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Nightsquad Commando",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479618&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Obosh, the Preypiercer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479748&type=card",
        cmc: "5",
        color: "Black or Red",
        type: "Creature",
    },
    {
        name: "Of One Mind",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479580&type=card",
        cmc: "3",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Offspring's Revenge",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479718&type=card",
        cmc: "5",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Ominous Seas",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479581&type=card",
        cmc: "2",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Pacifism",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479545&type=card",
        cmc: "2",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Parcelbeast",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479719&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Patagia Tiger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479546&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Perimeter Sergeant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479547&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Phase Dolphin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479582&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Plains",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=482535&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Plummet",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479689&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Pollywog Symbiote",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479583&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Porcuparrot",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479648&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Pouncing Shoreshark",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479584&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Prickly Marmoset",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479649&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Primal Empathy",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479720&type=card",
        cmc: "3",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Proud Wildbonder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479749&type=card",
        cmc: "4",
        color: "Red or Green",
        type: "Creature",
    },
    {
        name: "Pyroceratops",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479650&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Quartzwood Crasher",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479721&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Raking Claws",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479651&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Ram Through",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479690&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Raugrin Crystal",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479758&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Raugrin Triome",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479771&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Reconnaissance Mission",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479585&type=card",
        cmc: "4",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Regal Leosaur",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479722&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Reptilian Reflection",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479652&type=card",
        cmc: "3",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Rielle, the Everwise",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479723&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Rooting Moloch",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479653&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Rugged Highlands",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479772&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Ruinous Ultimatum",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479724&type=card",
        cmc: "7",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Rumbling Rockslide",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479654&type=card",
        cmc: "4",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Sanctuary Lockdown",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479548&type=card",
        cmc: "3",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Sanctuary Smasher",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479655&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Savai Crystal",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479759&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Savai Sabertooth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479549&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Savai Thundermane",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479725&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
];
const ikoria_page3 = [
    {
        name: "Savai Triome",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479773&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Scoured Barrens",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479774&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Sea-Dasher Octopus",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479586&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Serrated Scorpion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479619&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Shark Typhoon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479587&type=card",
        cmc: "6",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Shredded Sails",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479656&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Skull Prophet",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479726&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Skycat Sovereign",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479727&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Sleeper Dart",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479760&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Slitherwisp",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479728&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Snapdax, Apex of the Hunt",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479729&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Snare Tactician",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479550&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Solid Footing",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479551&type=card",
        cmc: "1",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Song of Creation",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479730&type=card",
        cmc: "4",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Sonorous Howlbonder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479750&type=card",
        cmc: "3",
        color: "Black or Red",
        type: "Creature",
    },
    {
        name: "Spelleater Wolverine",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479657&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Splendor Mare",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479552&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Spontaneous Flight",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479553&type=card",
        cmc: "3",
        color: "White",
        type: "Instant",
    },
    {
        name: "Springjaw Trap",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479761&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Sprite Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479731&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Startling Development",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479588&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Stormwild Capridor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479554&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Sudden Spinnerets",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479691&type=card",
        cmc: "1",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Suffocating Fumes",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479620&type=card",
        cmc: "3",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Survivors' Bond",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479692&type=card",
        cmc: "2",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Swallow Whole",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479555&type=card",
        cmc: "1",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Swamp",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=482541&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Swiftwater Cliffs",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479775&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Tentative Connection",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479658&type=card",
        cmc: "4",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "The Ozolith",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479757&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Thieving Otter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479589&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Thornwood Falls",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479776&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Thwart the Enemy",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479693&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Titanoth Rex",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479694&type=card",
        cmc: "9",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Titans' Nest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479732&type=card",
        cmc: "4",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Tranquil Cove",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479777&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Trumpeting Gnarr",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479733&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Umori, the Collector",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479751&type=card",
        cmc: "4",
        color: "Black or Green",
        type: "Creature",
    },
    {
        name: "Unbreakable Bond",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479621&type=card",
        cmc: "5",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Unexpected Fangs",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479622&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Unlikely Aid",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479623&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Unpredictable Cyclone",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479659&type=card",
        cmc: "5",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Vadrok, Apex of Thunder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479734&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Valiant Rescuer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479556&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Vivien, Monsters' Advocate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479695&type=card",
        cmc: "5",
        color: "Green",
        type: "Planeswalker",
    },
    {
        name: "Void Beckoner",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479624&type=card",
        cmc: "8",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Voracious Greatshark",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479590&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Vulpikeet",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479557&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Weaponize the Monsters",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479660&type=card",
        cmc: "1",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Whirlwind of Thought",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479735&type=card",
        cmc: "4",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Whisper Squad",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479625&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Will of the All-Hunter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479558&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Wilt",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479696&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Wind-Scarred Crag",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479778&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Wingfold Pteron",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479591&type=card",
        cmc: "6",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Wingspan Mentor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479592&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Winota, Joiner of Forces",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479736&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Yidaro, Wandering Monster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479661&type=card",
        cmc: "7",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Yorion, Sky Nomad",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479752&type=card",
        cmc: "5",
        color: "White or Blue",
        type: "Creature",
    },
    {
        name: "Zagoth Crystal",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479762&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Zagoth Mamba",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479626&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Zagoth Triome",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479779&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Zenith Flare",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479737&type=card",
        cmc: "4",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Zilortha, Strength Incarnate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=482524&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Zirda, the Dawnwaker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=479753&type=card",
        cmc: "3",
        color: "Red or White",
        type: "Creature",
    },
];

// this is the full Zendikar Rising array
export const ikoria = ikoria_page1.concat(ikoria_page2, ikoria_page3);

export const ikoriaObj = ikoria.reduce((acc, card) => {
    return {
        ...acc,
        [card.name]: {
            ["image"]: card.image,
            ["cmc"]: card.cmc,
            ["color"]: card.color,
            ["type"]: card.type,
        },
    };
}, {});
