//---------- Kaldheim ----------
const kaldheim_page1 = [
    {
        name: "Absorb Identity",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506925&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Aegar, the Freezing Flame",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503816&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Alpine Meadow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503864&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Alrund, God of the Cosmos",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503646&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Alrund's Epiphany",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503648&type=card",
        cmc: "7",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Annul",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503649&type=card",
        cmc: "1",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Arachnoform",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503772&type=card",
        cmc: "2",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Arctic Treeline",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503865&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Armed and Armored",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506921&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Arni Brokenbrow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503731&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Arni Slays the Troll",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503817&type=card",
        cmc: "2",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Ascendant Spirit",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503650&type=card",
        cmc: "1",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Ascent of the Worthy",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503818&type=card",
        cmc: "3",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Augury Raven",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503651&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Avalanche Caller",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503652&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Axgard Armory",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503866&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Axgard Braggart",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503605&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Axgard Cavalry",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503732&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Barkchannel Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503867&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Basalt Ravager",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503733&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Battershield Warrior",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503606&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Battle for Bretagard",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503819&type=card",
        cmc: "3",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Battle Mammoth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503773&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Battle of Frost and Fire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503820&type=card",
        cmc: "5",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Battlefield Raptor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503607&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Bearded Axe",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506930&type=card",
        cmc: "3",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Behold the Multiverse",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503653&type=card",
        cmc: "4",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Berg Strider",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503654&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Beskir Shieldmate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503608&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Bind the Monster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503655&type=card",
        cmc: "1",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Binding the Old Gods",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503822&type=card",
        cmc: "4",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Birgi, God of Storytelling",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503734&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Blessing of Frost",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503774&type=card",
        cmc: "4",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Blightstep Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503869&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Blizzard Brawl",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503775&type=card",
        cmc: "1",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Blood on the Snow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503687&type=card",
        cmc: "6",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Bloodline Pretender",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503851&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Bloodsky Berserker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503688&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Boreal Outrider",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503776&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Bound in Gold",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503609&type=card",
        cmc: "3",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Breakneck Berserker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503736&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Bretagard Stronghold",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503871&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Brinebarrow Intruder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503656&type=card",
        cmc: "1",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Broken Wings",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503777&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Burning-Rune Demon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503689&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Calamity Bearer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503737&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Canopy Tactician",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506920&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Cinderheart Giant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503738&type=card",
        cmc: "7",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Clarion Spirit",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503610&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Cleaving Reaper",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506918&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Codespell Cleric",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503611&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Colossal Plow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503852&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Cosima, God of the Voyage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503657&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Cosmos Charger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503659&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Cosmos Elixir",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503853&type=card",
        cmc: "4",
        color: "4",
        type: "Artifact",
    },
    {
        name: "Craven Hulk",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503739&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Crippling Fear",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503690&type=card",
        cmc: "4",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Crush the Weak",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503740&type=card",
        cmc: "3",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Cyclone Summoner",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503660&type=card",
        cmc: "7",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Darkbore Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503872&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Deathknell Berserker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503691&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Demon Bolt",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503741&type=card",
        cmc: "3",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Demonic Gifts",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503692&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Depart the Realm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503661&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Disdainful Stroke",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503662&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Divine Gambit",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503612&type=card",
        cmc: "2",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Dogged Pursuit",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503693&type=card",
        cmc: "4",
        color: "Black",
        type: undefined,
    },
    {
        name: "Doomskar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503613&type=card",
        cmc: "5",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Doomskar Oracle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503614&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Doomskar Titan",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503742&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Dragonkin Berserker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503743&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Draugr Necromancer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503694&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Draugr Recruiter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503695&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Draugr Thought-Thief",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503663&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Draugr's Helm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503696&type=card",
        cmc: "2",
        color: "Black",
        type: "Artifact",
    },
    {
        name: "Dread Rider",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503697&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Dream Devourer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503698&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Dual Strike",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503744&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Duskwielder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503699&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Dwarven Hammer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503745&type=card",
        cmc: "3",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Dwarven Reinforcements",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503746&type=card",
        cmc: "4",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Egon, God of Death",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503700&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Elderfang Disciple",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503702&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Elderfang Ritualist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506927&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Elderleaf Mentor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503778&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Elven Ambush",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506933&type=card",
        cmc: "4",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Elven Bow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503779&type=card",
        cmc: "1",
        color: "Green",
        type: "Artifact",
    },
    {
        name: "Elvish Warmaster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503780&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Eradicator Valkyrie",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503703&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Esika, God of the Tree",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503781&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Esika's Chariot",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503783&type=card",
        cmc: "4",
        color: "Green",
        type: "Artifact",
    },
    {
        name: "Faceless Haven",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503874&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Fall of the Impostor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503824&type=card",
        cmc: "3",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Fearless Liberator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503747&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Fearless Pup",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503748&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Feed the Serpent",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503704&type=card",
        cmc: "4",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Fire Giant's Fury",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506931&type=card",
        cmc: "2",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Firja, Judge of Valor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503825&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Firja's Retribution",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503826&type=card",
        cmc: "4",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Forest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=507589&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
];

const kaldheim_page2 = [
    {
        name: "Forging the Tyrite Sword",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503827&type=card",
        cmc: "3",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Frenzied Raider",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503749&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Frost Augur",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503664&type=card",
        cmc: "1",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Frost Bite",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503750&type=card",
        cmc: "1",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Frostpeak Yeti",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503665&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Frostpyre Arcanist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503666&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Funeral Longboat",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503854&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Fynn, the Fangbearer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503784&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Gates of Istfell",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503875&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Giant Ox",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503615&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Giant's Amulet",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503667&type=card",
        cmc: "1",
        color: "Blue",
        type: "Artifact",
    },
    {
        name: "Giant's Grasp",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506926&type=card",
        cmc: "4",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Gilded Assault Cart",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506932&type=card",
        cmc: "3",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Glacial Floodplain",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503876&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Gladewalker Ritualist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506934&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Glimpse the Cosmos",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503668&type=card",
        cmc: "2",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Glittering Frost",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503785&type=card",
        cmc: "3",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Glorious Protector",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503616&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Gnottvold Recluse",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503786&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Gnottvold Slumbermound",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503877&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Gods' Hall Guardian",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503617&type=card",
        cmc: "6",
        color: "White",
        type: "Creature",
    },
    {
        name: "Goldmaw Champion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503618&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Goldspan Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503751&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Goldvein Pick",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503855&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Graven Lore",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503669&type=card",
        cmc: "5",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Great Hall of Starnheim",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503878&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Grim Draugr",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503705&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Grizzled Outrider",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503787&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Guardian Gladewalker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503788&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Hagi Mob",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503752&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Hailstorm Valkyrie",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503706&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Hakka, Whispering Raven",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503647&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Halvar, God of Battle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503619&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Harald Unites the Elves",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503829&type=card",
        cmc: "4",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Harald, King of Skemfar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503828&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Harnfel, Horn of Bounty",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503735&type=card",
        cmc: "5",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Haunting Voyage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503707&type=card",
        cmc: "6",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Hengegate Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503879&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Highland Forest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503881&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Horizon Seeker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503789&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Ice Tunnel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503882&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Icebind Pillar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503670&type=card",
        cmc: "3",
        color: "Blue",
        type: "Artifact",
    },
    {
        name: "Icebreaker Kraken",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503671&type=card",
        cmc: "12",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Icehide Troll",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503790&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Immersturm Predator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503830&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Immersturm Raider",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503753&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Immersturm Skullcairn",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503883&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "In Search of Greatness",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503791&type=card",
        cmc: "2",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Infernal Pet",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503708&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Inga Rune-Eyes",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503672&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Invasion of the Giants",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503831&type=card",
        cmc: "2",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Invoke the Divine",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503621&type=card",
        cmc: "3",
        color: "White",
        type: "Instant",
    },
    {
        name: "Iron Verdict",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503622&type=card",
        cmc: "3",
        color: "White",
        type: "Instant",
    },
    {
        name: "Island",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=507586&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Jarl of the Forsaken",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503709&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Jaspera Sentinel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503792&type=card",
        cmc: "1",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Jorn, God of Winter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503793&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Kaldring, the Rimestaff",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503794&type=card",
        cmc: "3",
        color: "Blue",
        type: "Artifact",
    },
    {
        name: "Kardur, Doomscourge",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503832&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Kardur's Vicious Return",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503833&type=card",
        cmc: "4",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Karfell Harbinger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503673&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Karfell Kennel-Master",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503710&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Kaya the Inexorable",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503834&type=card",
        cmc: "5",
        color: "White",
        type: "Planeswalker",
    },
    {
        name: "Kaya's Onslaught",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503623&type=card",
        cmc: "3",
        color: "White",
        type: "Instant",
    },
    {
        name: "King Harald's Revenge",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503795&type=card",
        cmc: "3",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "King Narfi's Betrayal",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503835&type=card",
        cmc: "3",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Koll, the Forgemaster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503836&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Kolvori, God of Kinship",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503796&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Koma, Cosmos Serpent",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503837&type=card",
        cmc: "7",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Koma's Faithful",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503711&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Littjara Glade-Warden",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503798&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Littjara Kinseekers",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503674&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Littjara Mirrorlake",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503884&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Magda, Brazen Outlaw",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503754&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Maja, Bretagard Protector",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503838&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Mammoth Growth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503799&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Masked Vandal",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503800&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Maskwood Nexus",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503856&type=card",
        cmc: "4",
        color: "4",
        type: "Artifact",
    },
    {
        name: "Master Skald",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503624&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Mistgate Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503880&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Mists of Littjara",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503675&type=card",
        cmc: "2",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Mistwalker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503676&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Moritte of the Frost",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503839&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Mountain",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=507588&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Mystic Reflection",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503677&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Narfi, Betrayer King",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503840&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Niko Aris",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503841&type=card",
        cmc: "3",
        color: "White",
        type: "Planeswalker",
    },
    {
        name: "Niko Defies Destiny",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503842&type=card",
        cmc: "3",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Old-Growth Troll",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503801&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Open the Omenpaths",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503755&type=card",
        cmc: "3",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Orvar, the All-Form",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503678&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Path to the World Tree",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503802&type=card",
        cmc: "2",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Pilfering Hawk",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503679&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Plains",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=507585&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Poison the Cup",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503712&type=card",
        cmc: "3",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Port of Karfell",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503885&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Priest of the Haunted Edge",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503713&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Provoke the Trolls",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503756&type=card",
        cmc: "4",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Pyre of Heroes",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503857&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Quakebringer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503757&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
];

const kaldheim_page3 = [
    {
        name: "Raiders' Karve",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503858&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Raise the Draugr",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503714&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Rally the Ranks",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503625&type=card",
        cmc: "2",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Rampage of the Valkyries",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506935&type=card",
        cmc: "5",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Raven Wings",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503859&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Ravenform",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503680&type=card",
        cmc: "3",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Ravenous Lindwurm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503803&type=card",
        cmc: "6",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Realmwalker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503804&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Reckless Crew",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503758&type=card",
        cmc: "4",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Reflections of Littjara",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503681&type=card",
        cmc: "5",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Reidane, God of the Worthy",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503626&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Renegade Reaper",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506928&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Replicating Ring",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503860&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Resplendent Marshal",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503628&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Return Upon the Tide",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503715&type=card",
        cmc: "5",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Revitalize",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503629&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Righteous Valkyrie",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503630&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Rimewood Falls",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503886&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Rise of the Dread Marn",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503716&type=card",
        cmc: "3",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Rootless Yew",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503805&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Roots of Wisdom",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503806&type=card",
        cmc: "2",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Run Amok",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503759&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Run Ashore",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503682&type=card",
        cmc: "6",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Rune of Flight",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503683&type=card",
        cmc: "2",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Rune of Might",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503807&type=card",
        cmc: "2",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Rune of Mortality",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503717&type=card",
        cmc: "2",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Rune of Speed",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503760&type=card",
        cmc: "2",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Rune of Sustenance",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503631&type=card",
        cmc: "2",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Runed Crown",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503861&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Runeforge Champion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503632&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Sarulf, Realm Eater",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503844&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Sarulf's Packmate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503808&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Saw It Coming",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503684&type=card",
        cmc: "3",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Scorn Effigy",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503862&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Sculptor of Winter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503809&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Search for Glory",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503633&type=card",
        cmc: "3",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Searstep Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503870&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Seize the Spoils",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503761&type=card",
        cmc: "3",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Shackles of Treachery",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503762&type=card",
        cmc: "3",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Shepherd of the Cosmos",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503634&type=card",
        cmc: "6",
        color: "White",
        type: "Creature",
    },
    {
        name: "Shimmerdrift Vale",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503887&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Showdown of the Skalds",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503845&type=card",
        cmc: "4",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Sigrid, God-Favored",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503635&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Skemfar Avenger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503718&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Skemfar Elderhall",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503888&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Skemfar Shadowsage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503719&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Skull Raid",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503720&type=card",
        cmc: "4",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Slitherbore Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503873&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Smashing Success",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503763&type=card",
        cmc: "4",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Snakeskin Veil",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503810&type=card",
        cmc: "1",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Snow-Covered Forest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503904&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Snow-Covered Island",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503898&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Snow-Covered Mountain",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503902&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Snow-Covered Plains",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503896&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Snow-Covered Swamp",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503900&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Snowfield Sinkhole",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503889&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Spectral Steel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503636&type=card",
        cmc: "2",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Spirit of the Aldergard",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503811&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Squash",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503764&type=card",
        cmc: "5",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Stalwart Valkyrie",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503637&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Starnheim Aspirant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506922&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Starnheim Courser",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503638&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Starnheim Unleashed",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503639&type=card",
        cmc: "4",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Story Seeker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503640&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Strategic Planning",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503685&type=card",
        cmc: "2",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Struggle for Skemfar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503812&type=card",
        cmc: "4",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Sulfurous Mire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503890&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Surtland Elementalist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506917&type=card",
        cmc: "7",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Surtland Flinger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506919&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Surtland Frostpyre",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503891&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Svella, Ice Shaper",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503846&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Swamp",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=507587&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Sword of the Realms",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503620&type=card",
        cmc: "2",
        color: "White",
        type: "Artifact",
    },
    {
        name: "Tergrid, God of Fright",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503721&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Tergrid's Lantern",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503722&type=card",
        cmc: "4",
        color: "Black",
        type: "Artifact",
    },
    {
        name: "Tergrid's Shadow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503723&type=card",
        cmc: "5",
        color: "Black",
        type: "Instant",
    },
    {
        name: "The Bears of Littjara",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503821&type=card",
        cmc: "3",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "The Bloodsky Massacre",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503823&type=card",
        cmc: "3",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "The Omenkeel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503658&type=card",
        cmc: "2",
        color: "Blue",
        type: "Artifact",
    },
    {
        name: "The Prismatic Bridge",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503782&type=card",
        cmc: "5",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "The Raven's Warning",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503843&type=card",
        cmc: "3",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "The Ringhart Crest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503797&type=card",
        cmc: "2",
        color: "Green",
        type: "Artifact",
    },
    {
        name: "The Three Seasons",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503847&type=card",
        cmc: "2",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "The Trickster-God's Heist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503848&type=card",
        cmc: "4",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "The World Tree",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503895&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Thornmantle Striker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506929&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Throne of Death",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503701&type=card",
        cmc: "1",
        color: "Black",
        type: "Artifact",
    },
    {
        name: "Tibalt, Cosmic Impostor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503725&type=card",
        cmc: "7",
        color: "Black",
        type: "Planeswalker",
    },
    {
        name: "Tibalt's Trickery",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503765&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Tidechannel Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503868&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Toralf, God of Fury",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503766&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Toralf's Hammer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503767&type=card",
        cmc: "2",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Tormentor's Helm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503768&type=card",
        cmc: "1",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Toski, Bearer of Secrets",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503813&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Tundra Fumarole",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503769&type=card",
        cmc: "3",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Tuskeri Firewalker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503770&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Tyrite Sanctum",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503892&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Tyvar Kell",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503814&type=card",
        cmc: "4",
        color: "Green",
        type: "Planeswalker",
    },
    {
        name: "Undersea Invader",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503686&type=card",
        cmc: "6",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Usher of the Fallen",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503641&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
];

const kaldheim_page4 = [
    {
        name: "Valki, God of Lies",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503724&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Valkmira, Protector's Shield",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503627&type=card",
        cmc: "4",
        color: "White",
        type: "Artifact",
    },
    {
        name: "Valkyrie Harbinger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506916&type=card",
        cmc: "6",
        color: "White",
        type: "Creature",
    },
    {
        name: "Valkyrie's Sword",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503642&type=card",
        cmc: "2",
        color: "White",
        type: "Artifact",
    },
    {
        name: "Valor of the Worthy",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503643&type=card",
        cmc: "1",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Varragoth, Bloodsky Sire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503726&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Vault Robber",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503771&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Vega, the Watcher",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503849&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Vengeful Reaper",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503727&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Village Rites",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503728&type=card",
        cmc: "1",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Volatile Fjord",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503893&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Vorinclex, Monstrous Raider",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503815&type=card",
        cmc: "6",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Waking the Trolls",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503850&type=card",
        cmc: "6",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Warchanter Skald",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506923&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Warhorn Blast",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503644&type=card",
        cmc: "5",
        color: "White",
        type: "Instant",
    },
    {
        name: "Weathered Runestone",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503863&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Weigh Down",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503729&type=card",
        cmc: "1",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Wings of the Cosmos",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503645&type=card",
        cmc: "1",
        color: "White",
        type: "Instant",
    },
    {
        name: "Withercrown",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503730&type=card",
        cmc: "2",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Woodland Chasm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503894&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Youthful Valkyrie",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506924&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
];

export const kaldheim = kaldheim_page1.concat(kaldheim_page2, kaldheim_page3, kaldheim_page4);
export const kaldheimObj = kaldheim.reduce((acc, card) => {
    return {
        ...acc,
        [card.name]: {
            ["image"]: card.image,
            ["cmc"]: card.cmc,
            ["color"]: card.color,
            ["type"]: card.type,
        },
    };
}, {});
