//---------- Kaldheim ----------
const kaldheim_page1 = [
    {
        name: "Absorb Identity",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506925&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Aegar, the Freezing Flame",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503816&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Alpine Meadow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503864&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Alrund, God of the Cosmos",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503646&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Alrund's Epiphany",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503648&type=card",
        cmc: "7",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Annul",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503649&type=card",
        cmc: "1",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Arachnoform",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503772&type=card",
        cmc: "2",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Arctic Treeline",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503865&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Armed and Armored",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506921&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Arni Brokenbrow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503731&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Arni Slays the Troll",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503817&type=card",
        cmc: "2",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Ascendant Spirit",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503650&type=card",
        cmc: "1",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Ascent of the Worthy",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503818&type=card",
        cmc: "3",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Augury Raven",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503651&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Avalanche Caller",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503652&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Axgard Armory",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503866&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Axgard Braggart",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503605&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Axgard Cavalry",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503732&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Barkchannel Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503867&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Basalt Ravager",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503733&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Battershield Warrior",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503606&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Battle for Bretagard",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503819&type=card",
        cmc: "3",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Battle Mammoth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503773&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Battle of Frost and Fire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503820&type=card",
        cmc: "5",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Battlefield Raptor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503607&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Bearded Axe",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506930&type=card",
        cmc: "3",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Behold the Multiverse",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503653&type=card",
        cmc: "4",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Berg Strider",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503654&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Beskir Shieldmate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503608&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Bind the Monster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503655&type=card",
        cmc: "1",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Binding the Old Gods",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503822&type=card",
        cmc: "4",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Birgi, God of Storytelling",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503734&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Blessing of Frost",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503774&type=card",
        cmc: "4",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Blightstep Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503869&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Blizzard Brawl",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503775&type=card",
        cmc: "1",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Blood on the Snow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503687&type=card",
        cmc: "6",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Bloodline Pretender",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503851&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Bloodsky Berserker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503688&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Boreal Outrider",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503776&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Bound in Gold",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503609&type=card",
        cmc: "3",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Breakneck Berserker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503736&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Bretagard Stronghold",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503871&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Brinebarrow Intruder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503656&type=card",
        cmc: "1",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Broken Wings",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503777&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Burning-Rune Demon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503689&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Calamity Bearer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503737&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Canopy Tactician",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506920&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Cinderheart Giant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503738&type=card",
        cmc: "7",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Clarion Spirit",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503610&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Cleaving Reaper",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506918&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Codespell Cleric",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503611&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Colossal Plow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503852&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Cosima, God of the Voyage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503657&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Cosmos Charger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503659&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Cosmos Elixir",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503853&type=card",
        cmc: "4",
        color: "4",
        type: "Artifact",
    },
    {
        name: "Craven Hulk",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503739&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Crippling Fear",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503690&type=card",
        cmc: "4",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Crush the Weak",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503740&type=card",
        cmc: "3",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Cyclone Summoner",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503660&type=card",
        cmc: "7",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Darkbore Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503872&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Deathknell Berserker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503691&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Demon Bolt",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503741&type=card",
        cmc: "3",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Demonic Gifts",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503692&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Depart the Realm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503661&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Disdainful Stroke",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503662&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Divine Gambit",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503612&type=card",
        cmc: "2",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Dogged Pursuit",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503693&type=card",
        cmc: "4",
        color: "Black",
        type: undefined,
    },
    {
        name: "Doomskar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503613&type=card",
        cmc: "5",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Doomskar Oracle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503614&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Doomskar Titan",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503742&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Dragonkin Berserker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503743&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Draugr Necromancer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503694&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Draugr Recruiter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503695&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Draugr Thought-Thief",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503663&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Draugr's Helm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503696&type=card",
        cmc: "2",
        color: "Black",
        type: "Artifact",
    },
    {
        name: "Dread Rider",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503697&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Dream Devourer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503698&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Dual Strike",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503744&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Duskwielder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503699&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Dwarven Hammer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503745&type=card",
        cmc: "3",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Dwarven Reinforcements",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503746&type=card",
        cmc: "4",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Egon, God of Death",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503700&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Elderfang Disciple",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503702&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Elderfang Ritualist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506927&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Elderleaf Mentor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503778&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Elven Ambush",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506933&type=card",
        cmc: "4",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Elven Bow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503779&type=card",
        cmc: "1",
        color: "Green",
        type: "Artifact",
    },
    {
        name: "Elvish Warmaster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503780&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Eradicator Valkyrie",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503703&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Esika, God of the Tree",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503781&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Esika's Chariot",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503783&type=card",
        cmc: "4",
        color: "Green",
        type: "Artifact",
    },
    {
        name: "Faceless Haven",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503874&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Fall of the Impostor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503824&type=card",
        cmc: "3",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Fearless Liberator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503747&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Fearless Pup",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503748&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Feed the Serpent",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503704&type=card",
        cmc: "4",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Fire Giant's Fury",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506931&type=card",
        cmc: "2",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Firja, Judge of Valor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503825&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Firja's Retribution",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503826&type=card",
        cmc: "4",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Forest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=507589&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
];
