const zendikarRising = [
    {
        name: "Acquisitions Expert",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491722&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Adventure Awaits",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491822&type=card",
        cmc: "2",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Agadeem, the Undercrypt",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491724&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Agadeem's Awakening",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491723&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Akiri, Fearless Voyager",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491871&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Akoum Hellhound",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491772&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Akoum Teeth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491774&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Akoum Warrior",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491773&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Allied Assault",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491622&type=card",
        cmc: "3",
        color: "White",
        type: "Instant",
    },
    {
        name: "Ancient Greenwarden",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491823&type=card",
        cmc: "6",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Angel of Destiny",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491623&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Angelheart Protector",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491624&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Anticognition",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491672&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Archon of Emeria",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491625&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Archpriest of Iona",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491626&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Ardent Electromancer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491775&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Ashaya, Soul of the Wild",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491824&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Attended Healer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491627&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Bala Ged Recovery",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491825&type=card",
        cmc: "3",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Bala Ged Sanctuary",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491826&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Base Camp",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491908&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Beyeen Coast",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491674&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Beyeen Veil",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491673&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Blackbloom Bog",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491726&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Blackbloom Rogue",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491725&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Blood Beckoning",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491727&type=card",
        cmc: "1",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Blood Price",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491728&type=card",
        cmc: "4",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Bloodchief's Thirst",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491729&type=card",
        cmc: "1",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Boulderloft Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491910&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Branchloft Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491909&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Brightclimb Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491911&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Broken Wings",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491827&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Brushfire Elemental",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491872&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Bubble Snare",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491675&type=card",
        cmc: "1",
        color: "Blue",
        type: "Enchantmen",
    },
    {
        name: "Canopy Baloth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491828&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Canyon Jerboa",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491628&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Cascade Seer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491676&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Charix, the Raging Isle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491677&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Chilling Trap",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491678&type=card",
        cmc: "1",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Cinderclasm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491776&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Cleansing Wildfire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491777&type=card",
        cmc: "2",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Clearwater Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491913&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Cleric of Chill Depths",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491679&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Cleric of Life's Bond",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491873&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Cliffhaven Kitesail",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491894&type=card",
        cmc: "1",
        color: "1",
        type: "Artifac",
    },
    {
        name: "Cliffhaven Sell-Sword",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491629&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Concerted Defense",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491680&type=card",
        cmc: "1",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Confounding Conundrum",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491681&type=card",
        cmc: "2",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Coralhelm Chronicler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491682&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Coveted Prize",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491730&type=card",
        cmc: "5",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Cragcrown Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491915&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Cragplate Baloth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491829&type=card",
        cmc: "7",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Crawling Barrens",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491917&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Cunning Geysermage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491683&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Dauntless Survivor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491830&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Dauntless Unity",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491630&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Deadly Alliance",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491731&type=card",
        cmc: "5",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Deliberate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491684&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Demon's Disciple",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491732&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Disenchant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491631&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Drana, the Last Bloodchief",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491733&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Drana's Silencer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491734&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Dreadwurm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491735&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Emeria Captain",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491632&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Emeria, Shattered Skyclave",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491634&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Emeria's Call",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491633&type=card",
        cmc: "7",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Expedition Champion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491778&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Expedition Diviner",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491685&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Expedition Healer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491635&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Expedition Skulker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491736&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Farsight Adept",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491636&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Fearless Fledgling",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491637&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Feed the Swarm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491737&type=card",
        cmc: "2",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Felidar Retreat",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491638&type=card",
        cmc: "4",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Field Research",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491686&type=card",
        cmc: "3",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Fireblade Charger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491779&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Fissure Wizard",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491780&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Forest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491936&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Forsaken Monument",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491895&type=card",
        cmc: "5",
        color: "5",
        type: "Artifact",
    },
    {
        name: "Ghastly Gloomhunter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491738&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Glacial Grasp",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491687&type=card",
        cmc: "3",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Glasspool Mimic",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491688&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Glasspool Shore",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491689&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Gnarlid Colony",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491831&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Goma Fada Vanguard",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491781&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Grakmaw, Skyclave Ravager",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491874&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Grimclimb Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491912&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Grotag Bug-Catcher",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491782&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Grotag Night-Runner",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491783&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Guul Draz Mucklord",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491739&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Hagra Broodpit",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491742&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Hagra Constrictor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491740&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Hagra Mauling",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491741&type=card",
        cmc: "4",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Highborn Vampire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491743&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Inordinate Rage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491784&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Inscription of Abundance",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491832&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Inscription of Insight",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491690&type=card",
        cmc: "4",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Inscription of Ruin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491744&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Into the Roil",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491691&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Iridescent Hornbeetle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491833&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
];

let reducedZendikar = zendikarRising.reduce((acc, card) => {
    return { ...acc, [card.name]: { ["image"]: card.image, ["cmc"]: card.cmc } };
}, {});

// take array of cards in our cube and look for each of those cards by name in the reducedZendikar object
// if the card matches with a card in the reducedZendikar object --> add the card object to a new array (updated collection)
// so now instead of just having the names of the cards in our cube, we have a object for each card that contains the img url, cmc, and type
