const zendikarRising = [
    {
        name: "Acquisitions Expert",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491722&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Adventure Awaits",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491822&type=card",
        cmc: "2",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Agadeem, the Undercrypt",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491724&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Agadeem's Awakening",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491723&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Akiri, Fearless Voyager",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491871&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Akoum Hellhound",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491772&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Akoum Teeth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491774&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Akoum Warrior",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491773&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Allied Assault",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491622&type=card",
        cmc: "3",
        color: "White",
        type: "Instant",
    },
    {
        name: "Ancient Greenwarden",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491823&type=card",
        cmc: "6",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Angel of Destiny",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491623&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Angelheart Protector",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491624&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Anticognition",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491672&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Archon of Emeria",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491625&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Archpriest of Iona",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491626&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Ardent Electromancer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491775&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Ashaya, Soul of the Wild",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491824&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Attended Healer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491627&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Bala Ged Recovery",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491825&type=card",
        cmc: "3",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Bala Ged Sanctuary",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491826&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Base Camp",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491908&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Beyeen Coast",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491674&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Beyeen Veil",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491673&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Blackbloom Bog",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491726&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Blackbloom Rogue",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491725&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Blood Beckoning",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491727&type=card",
        cmc: "1",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Blood Price",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491728&type=card",
        cmc: "4",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Bloodchief's Thirst",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491729&type=card",
        cmc: "1",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Boulderloft Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491910&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Branchloft Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491909&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Brightclimb Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491911&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Broken Wings",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491827&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Brushfire Elemental",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491872&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Bubble Snare",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491675&type=card",
        cmc: "1",
        color: "Blue",
        type: "Enchantmen",
    },
    {
        name: "Canopy Baloth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491828&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Canyon Jerboa",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491628&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Cascade Seer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491676&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Charix, the Raging Isle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491677&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Chilling Trap",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491678&type=card",
        cmc: "1",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Cinderclasm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491776&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Cleansing Wildfire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491777&type=card",
        cmc: "2",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Clearwater Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491913&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Cleric of Chill Depths",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491679&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Cleric of Life's Bond",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491873&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Cliffhaven Kitesail",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491894&type=card",
        cmc: "1",
        color: "1",
        type: "Artifac",
    },
    {
        name: "Cliffhaven Sell-Sword",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491629&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Concerted Defense",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491680&type=card",
        cmc: "1",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Confounding Conundrum",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491681&type=card",
        cmc: "2",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Coralhelm Chronicler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491682&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Coveted Prize",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491730&type=card",
        cmc: "5",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Cragcrown Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491915&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Cragplate Baloth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491829&type=card",
        cmc: "7",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Crawling Barrens",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491917&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Cunning Geysermage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491683&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Dauntless Survivor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491830&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Dauntless Unity",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491630&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Deadly Alliance",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491731&type=card",
        cmc: "5",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Deliberate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491684&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Demon's Disciple",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491732&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Disenchant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491631&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Drana, the Last Bloodchief",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491733&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Drana's Silencer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491734&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Dreadwurm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491735&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Emeria Captain",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491632&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Emeria, Shattered Skyclave",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491634&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Emeria's Call",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491633&type=card",
        cmc: "7",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Expedition Champion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491778&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Expedition Diviner",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491685&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Expedition Healer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491635&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Expedition Skulker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491736&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Farsight Adept",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491636&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Fearless Fledgling",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491637&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Feed the Swarm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491737&type=card",
        cmc: "2",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Felidar Retreat",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491638&type=card",
        cmc: "4",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Field Research",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491686&type=card",
        cmc: "3",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Fireblade Charger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491779&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Fissure Wizard",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491780&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Forest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491936&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Forsaken Monument",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491895&type=card",
        cmc: "5",
        color: "5",
        type: "Artifact",
    },
    {
        name: "Ghastly Gloomhunter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491738&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Glacial Grasp",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491687&type=card",
        cmc: "3",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Glasspool Mimic",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491688&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Glasspool Shore",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491689&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Gnarlid Colony",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491831&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Goma Fada Vanguard",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491781&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Grakmaw, Skyclave Ravager",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491874&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Grimclimb Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491912&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Grotag Bug-Catcher",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491782&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Grotag Night-Runner",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491783&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Guul Draz Mucklord",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491739&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Hagra Broodpit",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491742&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Hagra Constrictor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491740&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Hagra Mauling",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491741&type=card",
        cmc: "4",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Highborn Vampire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491743&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Inordinate Rage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491784&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Inscription of Abundance",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491832&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Inscription of Insight",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491690&type=card",
        cmc: "4",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Inscription of Ruin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491744&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Into the Roil",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491691&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Iridescent Hornbeetle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491833&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
];

const adventureForgottenRealms = [
    {
        name: "Aberrant Mind Sorcerer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527331&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Acererak the Archlich",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527374&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Adult Gold Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527503&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Air-Cult Elemental",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527332&type=card",
        cmc: "6",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Arborea Pegasus",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527289&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Arcane Investigator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527333&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Armory Veteran",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527417&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Asmodeus the Archfiend",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527375&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Bag of Holding",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527527&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Baleful Beholder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527376&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Bar the Gate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527334&type=card",
        cmc: "3",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Barbarian Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527418&type=card",
        cmc: "1",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Bard Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527504&type=card",
        cmc: "2",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Barrowin of Clan Undurr",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527505&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Battle Cry Goblin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527419&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Black Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527377&type=card",
        cmc: "7",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Blink Dog",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527290&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Blue Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527336&type=card",
        cmc: "7",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Boots of Speed",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527420&type=card",
        cmc: "1",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Brazen Dwarf",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527421&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Bruenor Battlehammer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527506&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Bulette",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527460&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Bull's Strength",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527461&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Burning Hands",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527422&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Cave of the Frost Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527540&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Celestial Unicorn",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527292&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Chaos Channeler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527423&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Charmed Sleep",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527337&type=card",
        cmc: "3",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Check for Traps",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527379&type=card",
        cmc: "2",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Choose Your Weapon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527462&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Circle of Dreams Druid",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527463&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Circle of the Moon Druid",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527464&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Clattering Skeletons",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527380&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Cleric Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527293&type=card",
        cmc: "1",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Clever Conjurer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527338&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Cloister Gargoyle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527294&type=card",
        cmc: "3",
        color: "White",
        type: "Artifact",
    },
    {
        name: "Compelled Duel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527465&type=card",
        cmc: "2",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Contact Other Plane",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527339&type=card",
        cmc: "4",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Critical Hit",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527424&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Dancing Sword",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527295&type=card",
        cmc: "2",
        color: "White",
        type: "Artifact",
    },
    {
        name: "Dawnbringer Cleric",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527296&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Deadly Dispute",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527381&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Death-Priest of Myrkul",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527382&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Delina, Wild Mage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527425&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Delver's Torch",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527297&type=card",
        cmc: "2",
        color: "White",
        type: "Artifact",
    },
    {
        name: "Demilich",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527340&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Demogorgon's Clutches",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527383&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Den of the Bugbear",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527541&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Devoted Paladin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527298&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Devour Intellect",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527384&type=card",
        cmc: "1",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Dire Wolf Prowler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527466&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Displacer Beast",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527341&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Divine Smite",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527299&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Djinni Windseer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527342&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Dragon Turtle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527343&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Dragon's Disciple",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527300&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Dragon's Fire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527426&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Drider",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527385&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Drizzt Do'Urden",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527507&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Druid Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527467&type=card",
        cmc: "2",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Dueling Rapier",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527427&type=card",
        cmc: "1",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Dungeon Crawler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527386&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Dungeon Descent",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527542&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Dungeon Map",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527529&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Dungeon of the Mad Mage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=530447&type=card",
        cmc: "0",
        color: undefined,
        type: undefined,
    },
    {
        name: "Dwarfhold Champion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527301&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Earth-Cult Elemental",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527428&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Ebondeath, Dracolich",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527387&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Eccentric Apprentice",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527344&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Ellywick Tumblestrum",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527468&type=card",
        cmc: "4",
        color: "Green",
        type: "Planeswalker",
    },
    {
        name: "Elturgard Ranger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527469&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Evolving Wilds",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527543&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Eye of Vecna",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527530&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Eyes of the Beholder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527388&type=card",
        cmc: "6",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Farideh, Devil's Chosen",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527508&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Farideh's Fireball",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527429&type=card",
        cmc: "5",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Fates' Reversal",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527389&type=card",
        cmc: "2",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Feign Death",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527390&type=card",
        cmc: "1",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Feywild Trickster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527345&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Fifty Feet of Rope",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527531&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Fighter Class",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527509&type=card",
        cmc: "2",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Find the Path",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527470&type=card",
        cmc: "3",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Flameskull",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527430&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Flumph",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527302&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Fly",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527346&type=card",
        cmc: "1",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Forest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=530172&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Forsworn Paladin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527391&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Froghemoth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527471&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Gelatinous Cube",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527392&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Gloom Stalker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527303&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Gnoll Hunter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527472&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Goblin Javelineer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527431&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Goblin Morningstar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527432&type=card",
        cmc: "2",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Grand Master of Flowers",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527304&type=card",
        cmc: "4",
        color: "White",
        type: "Planeswalker",
    },
    {
        name: "Grazilaxx, Illithid Scholar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527347&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Greataxe",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527532&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Green Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527473&type=card",
        cmc: "6",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Gretchen Titchwillow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527510&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Grim Bounty",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527393&type=card",
        cmc: "4",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Grim Wanderer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527394&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
];

const kaldheim = [
    {
        name: "Absorb Identity",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506925&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Aegar, the Freezing Flame",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503816&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Alpine Meadow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503864&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Alrund, God of the Cosmos",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503646&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Alrund's Epiphany",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503648&type=card",
        cmc: "7",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Annul",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503649&type=card",
        cmc: "1",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Arachnoform",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503772&type=card",
        cmc: "2",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Arctic Treeline",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503865&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Armed and Armored",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506921&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Arni Brokenbrow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503731&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Arni Slays the Troll",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503817&type=card",
        cmc: "2",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Ascendant Spirit",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503650&type=card",
        cmc: "1",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Ascent of the Worthy",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503818&type=card",
        cmc: "3",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Augury Raven",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503651&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Avalanche Caller",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503652&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Axgard Armory",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503866&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Axgard Braggart",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503605&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Axgard Cavalry",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503732&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Barkchannel Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503867&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Basalt Ravager",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503733&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Battershield Warrior",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503606&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Battle for Bretagard",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503819&type=card",
        cmc: "3",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Battle Mammoth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503773&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Battle of Frost and Fire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503820&type=card",
        cmc: "5",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Battlefield Raptor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503607&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Bearded Axe",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506930&type=card",
        cmc: "3",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Behold the Multiverse",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503653&type=card",
        cmc: "4",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Berg Strider",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503654&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Beskir Shieldmate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503608&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Bind the Monster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503655&type=card",
        cmc: "1",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Binding the Old Gods",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503822&type=card",
        cmc: "4",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Birgi, God of Storytelling",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503734&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Blessing of Frost",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503774&type=card",
        cmc: "4",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Blightstep Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503869&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Blizzard Brawl",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503775&type=card",
        cmc: "1",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Blood on the Snow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503687&type=card",
        cmc: "6",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Bloodline Pretender",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503851&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Bloodsky Berserker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503688&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Boreal Outrider",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503776&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Bound in Gold",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503609&type=card",
        cmc: "3",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Breakneck Berserker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503736&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Bretagard Stronghold",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503871&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Brinebarrow Intruder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503656&type=card",
        cmc: "1",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Broken Wings",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503777&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Burning-Rune Demon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503689&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Calamity Bearer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503737&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Canopy Tactician",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506920&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Cinderheart Giant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503738&type=card",
        cmc: "7",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Clarion Spirit",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503610&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Cleaving Reaper",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506918&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Codespell Cleric",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503611&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Colossal Plow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503852&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Cosima, God of the Voyage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503657&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Cosmos Charger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503659&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Cosmos Elixir",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503853&type=card",
        cmc: "4",
        color: "4",
        type: "Artifact",
    },
    {
        name: "Craven Hulk",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503739&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Crippling Fear",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503690&type=card",
        cmc: "4",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Crush the Weak",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503740&type=card",
        cmc: "3",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Cyclone Summoner",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503660&type=card",
        cmc: "7",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Darkbore Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503872&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Deathknell Berserker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503691&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Demon Bolt",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503741&type=card",
        cmc: "3",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Demonic Gifts",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503692&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Depart the Realm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503661&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Disdainful Stroke",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503662&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Divine Gambit",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503612&type=card",
        cmc: "2",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Dogged Pursuit",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503693&type=card",
        cmc: "4",
        color: "Black",
        type: undefined,
    },
    {
        name: "Doomskar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503613&type=card",
        cmc: "5",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Doomskar Oracle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503614&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Doomskar Titan",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503742&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Dragonkin Berserker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503743&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Draugr Necromancer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503694&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Draugr Recruiter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503695&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Draugr Thought-Thief",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503663&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Draugr's Helm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503696&type=card",
        cmc: "2",
        color: "Black",
        type: "Artifact",
    },
    {
        name: "Dread Rider",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503697&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Dream Devourer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503698&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Dual Strike",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503744&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Duskwielder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503699&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Dwarven Hammer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503745&type=card",
        cmc: "3",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Dwarven Reinforcements",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503746&type=card",
        cmc: "4",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Egon, God of Death",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503700&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Elderfang Disciple",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503702&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Elderfang Ritualist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506927&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Elderleaf Mentor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503778&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Elven Ambush",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506933&type=card",
        cmc: "4",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Elven Bow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503779&type=card",
        cmc: "1",
        color: "Green",
        type: "Artifact",
    },
    {
        name: "Elvish Warmaster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503780&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Eradicator Valkyrie",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503703&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Esika, God of the Tree",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503781&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Esika's Chariot",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503783&type=card",
        cmc: "4",
        color: "Green",
        type: "Artifact",
    },
    {
        name: "Faceless Haven",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503874&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Fall of the Impostor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503824&type=card",
        cmc: "3",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Fearless Liberator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503747&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Fearless Pup",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503748&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Feed the Serpent",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503704&type=card",
        cmc: "4",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Fire Giant's Fury",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=506931&type=card",
        cmc: "2",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Firja, Judge of Valor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503825&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Firja's Retribution",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503826&type=card",
        cmc: "4",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Forest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=507589&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
];

let reducedZendikar = zendikarRising.reduce((acc, card) => {
    return {
        ...acc,
        [card.name]: { ["image"]: card.image, ["cmc"]: card.cmc, ["color"]: card.color },
    };
}, {});

let cardName = "Acquisitions Expert";

console.log(reducedZendikar[cardName]);

// take array of cards in our cube and look for each of those cards by name in the reducedZendikar object
// if the card matches with a card in the reducedZendikar object --> add the card object to a new array (updated collection)
// so now instead of just having the names of the cards in our cube, we have a object for each card that contains the img url, cmc, and type
