const warOfTheSpark_page1 = [
    {
        name: "Ahn-Crop Invader",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461040&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Aid the Fallen",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461003&type=card",
        cmc: "2",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Ajani, the Greathearted",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461111&type=card",
        cmc: "4",
        color: "Green",
        type: "Planeswalker",
    },
    {
        name: "Ajani's Pridemate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460931&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Angrath, Captain of Chaos",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461154&type=card",
        cmc: "4",
        color: "Black or Red",
        type: "Planeswalker",
    },
    {
        name: "Angrath's Rampage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461112&type=card",
        cmc: "2",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Arboreal Grazer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461076&type=card",
        cmc: "1",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Arlinn, Voice of the Pack",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461077&type=card",
        cmc: "6",
        color: "Green",
        type: "Planeswalker",
    },
    {
        name: "Arlinn's Wolf",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461078&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Ashiok, Dream Render",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461155&type=card",
        cmc: "3",
        color: "Blue or Black",
        type: "Planeswalker",
    },
    {
        name: "Ashiok's Skulker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460967&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Augur of Bolas",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460968&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Aven Eternal",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460969&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Awakening of Vitu-Ghazi",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461079&type=card",
        cmc: "5",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Band Together",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461080&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Banehound",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461004&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Battlefield Promotion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460932&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Bioessence Hydra",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461113&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Blast Zone",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461171&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Bleeding Edge",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461005&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Blindblast",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461041&type=card",
        cmc: "3",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Bloom Hulk",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461081&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Bolas's Citadel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461006&type=card",
        cmc: "6",
        color: "Black",
        type: "Artifact",
    },
    {
        name: "Bolt Bend",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461042&type=card",
        cmc: "4",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Bond of Discipline",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460933&type=card",
        cmc: "5",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Bond of Flourishing",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461082&type=card",
        cmc: "2",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Bond of Insight",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460970&type=card",
        cmc: "4",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Bond of Passion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461043&type=card",
        cmc: "6",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Bond of Revival",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461007&type=card",
        cmc: "5",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Bulwark Giant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460934&type=card",
        cmc: "6",
        color: "White",
        type: "Creature",
    },
    {
        name: "Burning Prophet",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461044&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Callous Dismissal",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460971&type=card",
        cmc: "2",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Casualties of War",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461114&type=card",
        cmc: "6",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Centaur Nurturer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461083&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Chainwhip Cyclops",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461045&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Challenger Troll",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461084&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Chandra, Fire Artisan",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461046&type=card",
        cmc: "4",
        color: "Red",
        type: "Planeswalker",
    },
    {
        name: "Chandra's Pyrohelix",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461047&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Chandra's Triumph",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461048&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Charity Extractor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461008&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Charmed Stray",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460935&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Command the Dreadhorde",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461009&type=card",
        cmc: "6",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Commence the Endgame",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460972&type=card",
        cmc: "6",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Contentious Plan",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460973&type=card",
        cmc: "2",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Courage in Crisis",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461085&type=card",
        cmc: "3",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Cruel Celebrant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461115&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Crush Dissent",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460974&type=card",
        cmc: "4",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Cyclops Electromancer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461049&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Davriel, Rogue Shadowmage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461010&type=card",
        cmc: "3",
        color: "Black",
        type: "Planeswalker",
    },
    {
        name: "Davriel's Shadowfugue",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461011&type=card",
        cmc: "4",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Deathsprout",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461116&type=card",
        cmc: "4",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Defiant Strike",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460936&type=card",
        cmc: "1",
        color: "White",
        type: "Instant",
    },
    {
        name: "Deliver Unto Evil",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461012&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Demolish",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461050&type=card",
        cmc: "4",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Despark",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461117&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Desperate Lunge",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=463833&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Devouring Hellion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461051&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Divine Arrow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460937&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Domri, Anarch of Bolas",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461118&type=card",
        cmc: "3",
        color: "Red",
        type: "Planeswalker",
    },
    {
        name: "Domri's Ambush",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461119&type=card",
        cmc: "2",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Dovin, Hand of Control",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461156&type=card",
        cmc: "3",
        color: "White or Blue",
        type: "Planeswalker",
    },
    {
        name: "Dovin's Veto",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461120&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Dreadhorde Arcanist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461052&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Dreadhorde Butcher",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461121&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Dreadhorde Invasion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461013&type=card",
        cmc: "2",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Dreadhorde Twins",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461053&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Dreadmalkin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461014&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Duskmantle Operative",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461015&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Elite Guardmage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461122&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Emergence Zone",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461172&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Enforcer Griffin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460938&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Enter the God-Eternals",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461123&type=card",
        cmc: "5",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Erratic Visionary",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460975&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Eternal Skylord",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460976&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Eternal Taskmaster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461017&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Evolution Sage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461086&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Fblthp, the Lost",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460977&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Feather, the Redeemed",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461124&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Finale of Devastation",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461087&type=card",
        cmc: "2",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Finale of Eternity",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461018&type=card",
        cmc: "2",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Finale of Glory",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460939&type=card",
        cmc: "2",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Finale of Promise",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461054&type=card",
        cmc: "2",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Finale of Revelation",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460978&type=card",
        cmc: "2",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Firemind Vessel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461164&type=card",
        cmc: "4",
        color: "4",
        type: "Artifact",
    },
    {
        name: "Flux Channeler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460979&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Forced Landing",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461088&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Forest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461189&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Gateway Plaza",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461173&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Giant Growth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461089&type=card",
        cmc: "1",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Gideon Blackblade",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460940&type=card",
        cmc: "3",
        color: "White",
        type: "Planeswalker",
    },
    {
        name: "Gideon, the Oathsworn",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=463832&type=card",
        cmc: "6",
        color: "White",
        type: "Planeswalker",
    },
    {
        name: "Gideon's Battle Cry",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=463834&type=card",
        cmc: "4",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Gideon's Company",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=463835&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Gideon's Sacrifice",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460941&type=card",
        cmc: "1",
        color: "White",
        type: "Instant",
    },
    {
        name: "Gideon's Triumph",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460942&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Gleaming Overseer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461125&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Goblin Assailant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461055&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Goblin Assault Team",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461056&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "God-Eternal Bontu",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461019&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "God-Eternal Kefnet",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460980&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
];
const warOfTheSpark_page2 = [
    {
        name: "God-Eternal Oketra",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460943&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "God-Eternal Rhonas",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461090&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "God-Pharaoh's Statue",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461165&type=card",
        cmc: "6",
        color: "6",
        type: "Artifact",
    },
    {
        name: "Grateful Apparition",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460944&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Grim Initiate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461057&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Guild Globe",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461166&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Guildpact Informant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=463838&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Heartfire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461058&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Heartwarming Redemption",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461126&type=card",
        cmc: "4",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Herald of the Dreadhorde",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461020&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Honor the God-Pharaoh",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461059&type=card",
        cmc: "3",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Huatli, the Sun's Heart",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461157&type=card",
        cmc: "3",
        color: "Green or White",
        type: "Planeswalker",
    },
    {
        name: "Huatli's Raptor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461127&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Ignite the Beacon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460945&type=card",
        cmc: "5",
        color: "White",
        type: "Instant",
    },
    {
        name: "Ilharg, the Raze-Boar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461060&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Interplanar Beacon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461174&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Invade the City",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461128&type=card",
        cmc: "3",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Invading Manticore",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461061&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Iron Bully",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461167&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Ironclad Krovod",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460946&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Island",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461180&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Jace, Arcane Strategist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=463837&type=card",
        cmc: "6",
        color: "Blue",
        type: "Planeswalker",
    },
    {
        name: "Jace, Wielder of Mysteries",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460981&type=card",
        cmc: "4",
        color: "Blue",
        type: "Planeswalker",
    },
    {
        name: "Jace's Projection",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=463839&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Jace's Ruse",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=463840&type=card",
        cmc: "5",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Jace's Triumph",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460982&type=card",
        cmc: "3",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Jaya, Venerated Firemage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461062&type=card",
        cmc: "5",
        color: "Red",
        type: "Planeswalker",
    },
    {
        name: "Jaya's Greeting",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461063&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Jiang Yanggu, Wildcrafter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461091&type=card",
        cmc: "3",
        color: "Green",
        type: "Planeswalker",
    },
    {
        name: "Karn, the Great Creator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460928&type=card",
        cmc: "4",
        color: "4",
        type: "Planeswalker",
    },
    {
        name: "Karn's Bastion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461175&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Kasmina, Enigmatic Mentor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460983&type=card",
        cmc: "4",
        color: "Blue",
        type: "Planeswalker",
    },
    {
        name: "Kasmina's Transmutation",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460984&type=card",
        cmc: "2",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Kaya, Bane of the Dead",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461158&type=card",
        cmc: "6",
        color: "White or Black",
        type: "Planeswalker",
    },
    {
        name: "Kaya's Ghostform",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461021&type=card",
        cmc: "1",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Kiora, Behemoth Beckoner",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461159&type=card",
        cmc: "3",
        color: "Green or Blue",
        type: "Planeswalker",
    },
    {
        name: "Kiora's Dambreaker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460985&type=card",
        cmc: "6",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Kraul Stinger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461092&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Krenko, Tin Street Kingpin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461064&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Kronch Wrangler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461093&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Law-Rune Enforcer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460947&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Lazotep Behemoth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461022&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Lazotep Plating",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460986&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Lazotep Reaver",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461023&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Leyline Prowler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461129&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Liliana, Dreadhorde General",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461024&type=card",
        cmc: "6",
        color: "Black",
        type: "Planeswalker",
    },
    {
        name: "Liliana's Triumph",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461025&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Living Twister",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461130&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Loxodon Sergeant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460948&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Makeshift Battalion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460949&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Mana Geode",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461168&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Martyr for the Cause",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460950&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Massacre Girl",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461026&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Mayhem Devil",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461131&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Merfolk Skydiver",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461132&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Mizzium Tank",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461065&type=card",
        cmc: "3",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Mobilized District",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461176&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Mountain",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461186&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Mowu, Loyal Companion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461094&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Naga Eternal",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460987&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Nahiri, Storm of Stone",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461160&type=card",
        cmc: "4",
        color: "Red or White",
        type: "Planeswalker",
    },
    {
        name: "Nahiri's Stoneblades",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461066&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Narset, Parter of Veils",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460988&type=card",
        cmc: "3",
        color: "Blue",
        type: "Planeswalker",
    },
    {
        name: "Narset's Reversal",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460989&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Neheb, Dreadhorde Champion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461067&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Neoform",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461133&type=card",
        cmc: "2",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "New Horizons",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461095&type=card",
        cmc: "3",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Nicol Bolas, Dragon-God",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461134&type=card",
        cmc: "5",
        color: "Black",
        type: "Planeswalker",
    },
    {
        name: "Nissa, Who Shakes the World",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461096&type=card",
        cmc: "5",
        color: "Green",
        type: "Planeswalker",
    },
    {
        name: "Nissa's Triumph",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461097&type=card",
        cmc: "2",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Niv-Mizzet Reborn",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461135&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "No Escape",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460990&type=card",
        cmc: "3",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Oath of Kaya",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461136&type=card",
        cmc: "3",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Ob Nixilis, the Hate-Twisted",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461027&type=card",
        cmc: "5",
        color: "Black",
        type: "Planeswalker",
    },
    {
        name: "Ob Nixilis's Cruelty",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461028&type=card",
        cmc: "3",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Orzhov Guildgate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=463836&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Paradise Druid",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461098&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Parhelion II",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460951&type=card",
        cmc: "8",
        color: "White",
        type: "Artifact",
    },
    {
        name: "Plains",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461177&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Planewide Celebration",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461099&type=card",
        cmc: "7",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Pledge of Unity",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461137&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Pollenbright Druid",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461100&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Pouncing Lynx",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460952&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Price of Betrayal",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461029&type=card",
        cmc: "1",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Primordial Wurm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461101&type=card",
        cmc: "6",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Prismite",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461169&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Prison Realm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460953&type=card",
        cmc: "3",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Raging Kronch",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461068&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Ral, Storm Conduit",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461138&type=card",
        cmc: "4",
        color: "Blue",
        type: "Planeswalker",
    },
    {
        name: "Rally of Wings",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460954&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Ral's Outburst",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461139&type=card",
        cmc: "4",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Ravnica at War",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460955&type=card",
        cmc: "4",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Relentless Advance",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460991&type=card",
        cmc: "4",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Rescuer Sphinx",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460992&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Return to Nature",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461102&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Rising Populace",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460956&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Roalesk, Apex Hybrid",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461140&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Role Reversal",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461141&type=card",
        cmc: "3",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Rubblebelt Rioters",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461142&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Saheeli, Sublime Artificer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461161&type=card",
        cmc: "3",
        color: "Blue or Red",
        type: "Planeswalker",
    },
];
const warOfTheSpark_page3 = [
    {
        name: "Saheeli's Silverwing",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461170&type=card",
        cmc: "4",
        color: "4",
        type: "Artifact",
    },
    {
        name: "Samut, Tyrant Smasher",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461162&type=card",
        cmc: "4",
        color: "Red or Green",
        type: "Planeswalker",
    },
    {
        name: "Samut's Sprint",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461069&type=card",
        cmc: "1",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Sarkhan the Masterless",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461070&type=card",
        cmc: "5",
        color: "Red",
        type: "Planeswalker",
    },
    {
        name: "Sarkhan's Catharsis",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461071&type=card",
        cmc: "5",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Shriekdiver",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461030&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Silent Submersible",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460993&type=card",
        cmc: "2",
        color: "Blue",
        type: "Artifact",
    },
    {
        name: "Simic Guildgate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=463841&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Single Combat",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460957&type=card",
        cmc: "5",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Sky Theater Strix",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460994&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Snarespinner",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461103&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Solar Blaze",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461143&type=card",
        cmc: "4",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Sorin, Vengeful Bloodlord",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461144&type=card",
        cmc: "4",
        color: "White",
        type: "Planeswalker",
    },
    {
        name: "Sorin's Thirst",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461031&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Soul Diviner",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461145&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Spark Double",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460995&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Spark Harvest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461032&type=card",
        cmc: "1",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Spark Reaper",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461033&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Spellgorger Weird",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461072&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Spellkeeper Weird",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460996&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Steady Aim",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461104&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Stealth Mission",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460997&type=card",
        cmc: "3",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Storm the Citadel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461105&type=card",
        cmc: "5",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Storrev, Devkarin Lich",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461146&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Sunblade Angel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460958&type=card",
        cmc: "6",
        color: "White",
        type: "Creature",
    },
    {
        name: "Swamp",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461183&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Tamiyo, Collector of Tales",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461147&type=card",
        cmc: "4",
        color: "Green",
        type: "Planeswalker",
    },
    {
        name: "Tamiyo's Epiphany",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460998&type=card",
        cmc: "4",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Teferi, Time Raveler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461148&type=card",
        cmc: "3",
        color: "White",
        type: "Planeswalker",
    },
    {
        name: "Teferi's Time Twist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460999&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Tenth District Legionnaire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461149&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Teyo, the Shieldmage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460959&type=card",
        cmc: "3",
        color: "White",
        type: "Planeswalker",
    },
    {
        name: "Teyo's Lightshield",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460960&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Tezzeret, Master of the Bridge",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=463842&type=card",
        cmc: "6",
        color: "Blue",
        type: "Planeswalker",
    },
    {
        name: "The Elderspell",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461016&type=card",
        cmc: "2",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "The Wanderer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460964&type=card",
        cmc: "4",
        color: "White",
        type: "Planeswalker",
    },
    {
        name: "Thunder Drake",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461000&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Thundering Ceratok",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461106&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Tibalt, Rakish Instigator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461073&type=card",
        cmc: "3",
        color: "Red",
        type: "Planeswalker",
    },
    {
        name: "Tibalt's Rager",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461074&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Time Wipe",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461150&type=card",
        cmc: "5",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Tithebearer Giant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461034&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Toll of the Invasion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461035&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Tolsimir, Friend to Wolves",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461151&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Tomik, Distinguished Advokist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460961&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Topple the Statue",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460962&type=card",
        cmc: "3",
        color: "White",
        type: "Instant",
    },
    {
        name: "Totally Lost",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461001&type=card",
        cmc: "5",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Trusted Pegasus",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460963&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Turret Ogre",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461075&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Tyrant's Scorn",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461152&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Ugin, the Ineffable",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460929&type=card",
        cmc: "6",
        color: "6",
        type: "Planeswalker",
    },
    {
        name: "Ugin's Conjurant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460930&type=card",
        cmc: "0",
        color: "Variable Colorless",
        type: "Creature",
    },
    {
        name: "Unlikely Aid",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461036&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Vampire Opportunist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461037&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Vivien, Champion of the Wilds",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461107&type=card",
        cmc: "3",
        color: "Green",
        type: "Planeswalker",
    },
    {
        name: "Vivien's Arkbow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461108&type=card",
        cmc: "2",
        color: "Green",
        type: "Artifact",
    },
    {
        name: "Vivien's Grizzly",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461109&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Vizier of the Scorpion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461038&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Vraska, Swarm's Eminence",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461163&type=card",
        cmc: "4",
        color: "Black or Green",
        type: "Planeswalker",
    },
    {
        name: "Vraska's Finisher",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461039&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Wall of Runes",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461002&type=card",
        cmc: "1",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Wanderer's Strike",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460965&type=card",
        cmc: "5",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "War Screecher",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=460966&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Wardscale Crocodile",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461110&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Widespread Brutality",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=461153&type=card",
        cmc: "4",
        color: "Black",
        type: "Sorcery",
    },
];

export const warOfTheSpark = warOfTheSpark_page1.concat(warOfTheSpark_page2, warOfTheSpark_page3);
export const warOfTheSparkObj = warOfTheSpark.reduce((acc, card) => {
    return {
        ...acc,
        [card.name]: {
            ["image"]: card.image,
            ["cmc"]: card.cmc,
            ["color"]: card.color,
            ["type"]: card.type,
        },
    };
}, {});
