//---------- Zendikar Rising ----------
export const zendikarRising_page1 = [
    {
        name: "Acquisitions Expert",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491722&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Adventure Awaits",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491822&type=card",
        cmc: "2",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Agadeem, the Undercrypt",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491724&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Agadeem's Awakening",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491723&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Akiri, Fearless Voyager",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491871&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Akoum Hellhound",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491772&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Akoum Teeth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491774&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Akoum Warrior",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491773&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Allied Assault",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491622&type=card",
        cmc: "3",
        color: "White",
        type: "Instant",
    },
    {
        name: "Ancient Greenwarden",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491823&type=card",
        cmc: "6",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Angel of Destiny",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491623&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Angelheart Protector",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491624&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Anticognition",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491672&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Archon of Emeria",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491625&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Archpriest of Iona",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491626&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Ardent Electromancer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491775&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Ashaya, Soul of the Wild",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491824&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Attended Healer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491627&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Bala Ged Recovery",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491825&type=card",
        cmc: "3",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Bala Ged Sanctuary",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491826&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Base Camp",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491908&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Beyeen Coast",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491674&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Beyeen Veil",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491673&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Blackbloom Bog",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491726&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Blackbloom Rogue",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491725&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Blood Beckoning",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491727&type=card",
        cmc: "1",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Blood Price",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491728&type=card",
        cmc: "4",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Bloodchief's Thirst",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491729&type=card",
        cmc: "1",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Boulderloft Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491910&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Branchloft Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491909&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Brightclimb Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491911&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Broken Wings",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491827&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Brushfire Elemental",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491872&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Bubble Snare",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491675&type=card",
        cmc: "1",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Canopy Baloth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491828&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Canyon Jerboa",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491628&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Cascade Seer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491676&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Charix, the Raging Isle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491677&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Chilling Trap",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491678&type=card",
        cmc: "1",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Cinderclasm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491776&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Cleansing Wildfire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491777&type=card",
        cmc: "2",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Clearwater Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491913&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Cleric of Chill Depths",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491679&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Cleric of Life's Bond",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491873&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Cliffhaven Kitesail",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491894&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Cliffhaven Sell-Sword",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491629&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Concerted Defense",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491680&type=card",
        cmc: "1",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Confounding Conundrum",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491681&type=card",
        cmc: "2",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Coralhelm Chronicler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491682&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Coveted Prize",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491730&type=card",
        cmc: "5",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Cragcrown Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491915&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Cragplate Baloth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491829&type=card",
        cmc: "7",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Crawling Barrens",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491917&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Cunning Geysermage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491683&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Dauntless Survivor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491830&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Dauntless Unity",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491630&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Deadly Alliance",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491731&type=card",
        cmc: "5",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Deliberate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491684&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Demon's Disciple",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491732&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Disenchant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491631&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Drana, the Last Bloodchief",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491733&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Drana's Silencer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491734&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Dreadwurm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491735&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Emeria Captain",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491632&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Emeria, Shattered Skyclave",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491634&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Emeria's Call",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491633&type=card",
        cmc: "7",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Expedition Champion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491778&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Expedition Diviner",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491685&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Expedition Healer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491635&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Expedition Skulker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491736&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Farsight Adept",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491636&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Fearless Fledgling",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491637&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Feed the Swarm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491737&type=card",
        cmc: "2",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Felidar Retreat",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491638&type=card",
        cmc: "4",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Field Research",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491686&type=card",
        cmc: "3",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Fireblade Charger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491779&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Fissure Wizard",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491780&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Forest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491936&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Forsaken Monument",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491895&type=card",
        cmc: "5",
        color: "5",
        type: "Artifact",
    },
    {
        name: "Ghastly Gloomhunter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491738&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Glacial Grasp",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491687&type=card",
        cmc: "3",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Glasspool Mimic",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491688&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Glasspool Shore",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491689&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Gnarlid Colony",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491831&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Goma Fada Vanguard",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491781&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Grakmaw, Skyclave Ravager",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491874&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Grimclimb Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491912&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Grotag Bug-Catcher",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491782&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Grotag Night-Runner",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491783&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Guul Draz Mucklord",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491739&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Hagra Broodpit",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491742&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Hagra Constrictor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491740&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Hagra Mauling",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491741&type=card",
        cmc: "4",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Highborn Vampire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491743&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Inordinate Rage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491784&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Inscription of Abundance",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491832&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Inscription of Insight",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491690&type=card",
        cmc: "4",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Inscription of Ruin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491744&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Into the Roil",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491691&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Iridescent Hornbeetle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491833&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
];
const zendikarRising_page2 = [
    {
        name: "Island",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491927&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Jace, Mirror Mage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491692&type=card",
        cmc: "3",
        color: "Blue",
        type: "Planeswalker",
    },
    {
        name: "Joraga Visionary",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491834&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Journey to Oblivion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491639&type=card",
        cmc: "5",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Jwari Disruption",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491693&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Jwari Ruins",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491694&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Kabira Outrider",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491640&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Kabira Plateau",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491642&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Kabira Takedown",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491641&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Kargan Intimidator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491785&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Kargan Warleader",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491875&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Kaza, Roil Chaser",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491876&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Kazandu Mammoth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491835&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Kazandu Nectarpot",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491837&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Kazandu Stomper",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491838&type=card",
        cmc: "6",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Kazandu Valley",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491836&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Kazuul's Cliffs",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491787&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Kazuul's Fury",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491786&type=card",
        cmc: "3",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Khalni Ambush",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491839&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Khalni Territory",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491840&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Kitesail Cleric",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491643&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Kor Blademaster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491644&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Kor Celebrant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491645&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Lavaglide Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491921&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Legion Angel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491646&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Leyline Tyrant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491788&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Linvala, Shield of Sea Gate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491877&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Lithoform Blight",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491745&type=card",
        cmc: "2",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Lithoform Engine",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491896&type=card",
        cmc: "4",
        color: "4",
        type: "Artifact",
    },
    {
        name: "Living Tempest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491695&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Lotus Cobra",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491841&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Lullmage's Domination",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491696&type=card",
        cmc: "3",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Lullmage's Familiar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491878&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Luminarch Aspirant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491647&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Maddening Cacophony",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491697&type=card",
        cmc: "2",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Magmatic Channeler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491789&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Makindi Mesas",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491650&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Makindi Ox",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491648&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Makindi Stampede",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491649&type=card",
        cmc: "5",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Malakir Blood-Priest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491746&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Malakir Mire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491748&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Malakir Rebirth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491747&type=card",
        cmc: "1",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Marauding Blight-Priest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491749&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Master of Winds",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491698&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Maul of the Skyclaves",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491651&type=card",
        cmc: "3",
        color: "White",
        type: "Artifact",
    },
    {
        name: "Merfolk Falconer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491699&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Merfolk Windrobber",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491700&type=card",
        cmc: "1",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Mesa Lynx",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491652&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Might of Murasa",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491842&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Mind Carver",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491750&type=card",
        cmc: "1",
        color: "Black",
        type: "Artifact",
    },
    {
        name: "Mind Drain",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491751&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Molten Blast",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491790&type=card",
        cmc: "3",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Moraug, Fury of Akoum",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491791&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Moss-Pit Skeleton",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491879&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Mountain",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491933&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Murasa Brute",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491843&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Murasa Rootgrazer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491880&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Murasa Sproutling",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491844&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Murkwater Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491914&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Myriad Construct",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491897&type=card",
        cmc: "4",
        color: "4",
        type: "Artifact",
    },
    {
        name: "Nahiri, Heir of the Ancients",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491881&type=card",
        cmc: "4",
        color: "Red",
        type: "Planeswalker",
    },
    {
        name: "Nahiri's Binding",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491653&type=card",
        cmc: "3",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Nahiri's Lithoforming",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491792&type=card",
        cmc: "2",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Needleverge Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491918&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Negate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491701&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Nighthawk Scavenger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491752&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Nimana Skitter-Sneak",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491753&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Nimana Skydancer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491754&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Nimble Trapfinder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491702&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Nissa of Shadowed Boughs",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491882&type=card",
        cmc: "4",
        color: "Black",
        type: "Planeswalker",
    },
    {
        name: "Nissa's Zendikon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491845&type=card",
        cmc: "4",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Nullpriest of Oblivion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491755&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Oblivion's Hunger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491756&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Omnath, Locus of Creation",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491883&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Ondu Inversion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491654&type=card",
        cmc: "8",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Ondu Skyruins",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491655&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Orah, Skyclave Hierophant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491884&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Oran-Rief Ooze",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491846&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Paired Tactician",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491656&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Pelakka Caverns",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491758&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Pelakka Predation",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491757&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Phylath, World Sculptor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491885&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Pillarverge Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491919&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Plains",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491924&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Practiced Tactics",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491657&type=card",
        cmc: "1",
        color: "White",
        type: "Instant",
    },
    {
        name: "Pressure Point",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491658&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Prowling Felidar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491659&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Pyroclastic Hellion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491793&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Rabid Bite",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491847&type=card",
        cmc: "2",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Ravager's Mace",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491886&type=card",
        cmc: "3",
        color: "Black",
        type: "Artifact",
    },
    {
        name: "Reclaim the Wastes",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491848&type=card",
        cmc: "1",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Relic Amulet",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491898&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Relic Axe",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491899&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Relic Golem",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491900&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Relic Robber",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491794&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Relic Vial",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491901&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Resolute Strike",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491660&type=card",
        cmc: "1",
        color: "White",
        type: "Instant",
    },
    {
        name: "Risen Riptide",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491703&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Riverglide Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491920&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Rockslide Sorcerer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491795&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
];
const zendikarRising_page3 = [
    {
        name: "Roil Eruption",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491796&type=card",
        cmc: "2",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Roiling Regrowth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491849&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Roiling Vortex",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491797&type=card",
        cmc: "2",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Roost of Drakes",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491704&type=card",
        cmc: "1",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Ruin Crab",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491705&type=card",
        cmc: "1",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Scale the Heights",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491850&type=card",
        cmc: "3",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Scavenged Blade",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491798&type=card",
        cmc: "2",
        color: "Red",
        type: "Artifact",
    },
    {
        name: "Scion of the Swarm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491759&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Scorch Rider",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491799&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Scourge of the Skyclaves",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491760&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Scute Swarm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491851&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Sea Gate Banneret",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491661&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Sea Gate Colossus",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491902&type=card",
        cmc: "7",
        color: "7",
        type: "Artifact",
    },
    {
        name: "Sea Gate Restoration",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491706&type=card",
        cmc: "7",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Sea Gate Stormcaller",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491708&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Sea Gate, Reborn",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491707&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Seafloor Stalker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491709&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Sejiri Glacier",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491663&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Sejiri Shelter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491662&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Shadow Stinger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491761&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Shadows' Verdict",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491762&type=card",
        cmc: "5",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Shatterskull Charger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491800&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Shatterskull Minotaur",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491801&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Shatterskull Smashing",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491802&type=card",
        cmc: "2",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Shatterskull, the Hammer Pass",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491803&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Shell Shield",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491710&type=card",
        cmc: "1",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Shepherd of Heroes",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491664&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Silundi Isle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491712&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Silundi Vision",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491711&type=card",
        cmc: "3",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Sizzling Barrage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491804&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Skyclave Apparition",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491665&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Skyclave Basilica",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491667&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Skyclave Cleric",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491666&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Skyclave Geopede",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491805&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Skyclave Pick-Axe",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491852&type=card",
        cmc: "1",
        color: "Green",
        type: "Artifact",
    },
    {
        name: "Skyclave Plunder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491713&type=card",
        cmc: "5",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Skyclave Relic",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491903&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Skyclave Sentinel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491904&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Skyclave Shade",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491763&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Skyclave Shadowcat",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491764&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Skyclave Squid",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491714&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Smite the Monstrous",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491669&type=card",
        cmc: "4",
        color: "White",
        type: "Instant",
    },
    {
        name: "Sneaking Guide",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491806&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Soaring Thought-Thief",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491887&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Song-Mad Ruins",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491808&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Song-Mad Treachery",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491807&type=card",
        cmc: "5",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Soul Shatter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491765&type=card",
        cmc: "3",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Spare Supplies",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491905&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Spikefield Cave",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491810&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Spikefield Hazard",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491809&type=card",
        cmc: "1",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Spitfire Lagac",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491811&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Spoils of Adventure",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491888&type=card",
        cmc: "6",
        color: "White",
        type: "Instant",
    },
    {
        name: "Springmantle Cleric",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491853&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Squad Commander",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491668&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Stonework Packbeast",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491906&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Strength of Solidarity",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491854&type=card",
        cmc: "1",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Subtle Strike",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491766&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Sure-Footed Infiltrator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491715&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Swamp",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491930&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Swarm Shambler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491855&type=card",
        cmc: "1",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Synchronized Spellcraft",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491812&type=card",
        cmc: "5",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Taborax, Hope's Demise",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491767&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Tajuru Blightblade",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491856&type=card",
        cmc: "1",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Tajuru Paragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491857&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Tajuru Snarecaster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491858&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Tangled Florahedron",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491859&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Tangled Vale",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491860&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Taunting Arbormage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491861&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Tazeem Raptor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491670&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Tazeem Roilmage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491716&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Tazri, Beacon of Unity",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491671&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Teeterpeak Ambusher",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491813&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Territorial Scythecat",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491862&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Thieving Skydiver",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491717&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Throne of Makindi",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491922&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Thundering Rebuke",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491814&type=card",
        cmc: "2",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Thundering Sparkmage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491815&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Thwart the Grave",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491768&type=card",
        cmc: "6",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Timbercrown Pathway",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491916&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Tormenting Voice",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491816&type=card",
        cmc: "2",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Tuktuk Rubblefort",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491817&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Turntimber Ascetic",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491863&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Turntimber Symbiosis",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491864&type=card",
        cmc: "7",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Turntimber, Serpentine Wood",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491865&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Umara Mystic",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491889&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Umara Skyfalls",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491719&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Umara Wizard",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491718&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Utility Knife",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491907&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Valakut Awakening",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491818&type=card",
        cmc: "3",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Valakut Exploration",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491820&type=card",
        cmc: "3",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Valakut Stoneforge",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491819&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Vanquish the Weak",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491769&type=card",
        cmc: "3",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Vastwood Fortification",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491866&type=card",
        cmc: "1",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Vastwood Surge",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491868&type=card",
        cmc: "4",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Vastwood Thicket",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491867&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Verazol, the Split Current",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491890&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Veteran Adventurer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491869&type=card",
        cmc: "6",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Vine Gecko",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491870&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Wayward Guide-Beast",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491821&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Windrider Wizard",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491720&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
];
const zendikarRising_page4 = [
    {
        name: "Yasharn, Implacable Earth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491891&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Zagras, Thief of Heartbeats",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491892&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Zareth San, the Trickster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491893&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Zof Bloodbog",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491771&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Zof Consumption",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491770&type=card",
        cmc: "6",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Zulaport Duelist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=491721&type=card",
        cmc: "1",
        color: "Blue",
        type: "Creature",
    },
];

// this is the full Zendikar Rising array
export const zendikarRising = zendikarRising_page1.concat(
    zendikarRising_page2,
    zendikarRising_page3,
    zendikarRising_page4
);

export const zendikarRisingObj = zendikarRising.reduce((acc, card) => {
    return {
        ...acc,
        [card.name]: {
            ["image"]: card.image,
            ["cmc"]: card.cmc,
            ["color"]: card.color,
            ["type"]: card.type,
        },
    };
}, {});
