const core2021_page1 = [
    {
        name: "Adherent of Hope",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488627&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Alchemist's Gift",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485410&type=card",
        cmc: "1",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Alpine Houndmaster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485538&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Alpine Watchdog",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485325&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Angelic Ascension",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485326&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Animal Sanctuary",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485565&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Anointed Chorister",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485327&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Archfiend's Vessel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485411&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Aven Gagglemaster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485328&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Azusa, Lost but Seeking",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485496&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Bad Deal",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485412&type=card",
        cmc: "6",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Baneslayer Angel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485329&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Barrin, Tolarian Archmage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485368&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Basri Ket",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485330&type=card",
        cmc: "3",
        color: "White",
        type: "Planeswalker",
    },
    {
        name: "Basri, Devoted Paladin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488626&type=card",
        cmc: "6",
        color: "White",
        type: "Planeswalker",
    },
    {
        name: "Basri's Acolyte",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485331&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Basri's Aegis",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488628&type=card",
        cmc: "4",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Basri's Lieutenant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485332&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Basri's Solidarity",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485333&type=card",
        cmc: "2",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Battle-Rattle Shaman",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485453&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Blood Glutton",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485413&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Bloodfell Caves",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485566&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Blossoming Sands",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485567&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Bolt Hound",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485454&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Bone Pit Brute",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485455&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Brash Taunter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485456&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Burlfist Oak",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485497&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Burn Bright",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485457&type=card",
        cmc: "3",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Caged Zombie",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485414&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Cancel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485369&type=card",
        cmc: "3",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Canopy Stalker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485498&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Capture Sphere",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485370&type=card",
        cmc: "4",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Carrion Grub",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485415&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Celestial Enforcer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485334&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Chandra, Flame's Catalyst",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488638&type=card",
        cmc: "6",
        color: "Red",
        type: "Planeswalker",
    },
    {
        name: "Chandra, Heart of Fire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485458&type=card",
        cmc: "5",
        color: "Red",
        type: "Planeswalker",
    },
    {
        name: "Chandra's Firemaw",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488639&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Chandra's Incinerator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485459&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Chandra's Magmutt",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485460&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Chandra's Pyreling",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485461&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Chromatic Orrery",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485551&type=card",
        cmc: "7",
        color: "7",
        type: "Artifact",
    },
    {
        name: "Chrome Replicator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485552&type=card",
        cmc: "5",
        color: "5",
        type: "Artifact",
    },
    {
        name: "Colossal Dreadmaw",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485499&type=card",
        cmc: "6",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Conclave Mentor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485539&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Concordia Pegasus",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485335&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Conspicuous Snoop",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485462&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Containment Priest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485336&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Crash Through",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485463&type=card",
        cmc: "1",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Crypt Lurker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485416&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Cultivate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485500&type=card",
        cmc: "3",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Daybreak Charger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485337&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Deathbloom Thallid",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485417&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Defiant Strike",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485338&type=card",
        cmc: "1",
        color: "White",
        type: "Instant",
    },
    {
        name: "Demonic Embrace",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485418&type=card",
        cmc: "3",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Destructive Tampering",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485464&type=card",
        cmc: "3",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Dire Fleet Warmonger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485540&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Discontinuity",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485371&type=card",
        cmc: "6",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Dismal Backwater",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485568&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Double Vision",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485465&type=card",
        cmc: "5",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Drowsing Tyrannodon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485501&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Dub",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485339&type=card",
        cmc: "3",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Duress",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485419&type=card",
        cmc: "1",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Elder Gargaroth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485502&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Eliminate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485420&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Enthralling Hold",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485372&type=card",
        cmc: "5",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Epitaph Golem",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485553&type=card",
        cmc: "5",
        color: "5",
        type: "Artifact",
    },
    {
        name: "Experimental Overload",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485541&type=card",
        cmc: "4",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Fabled Passage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485569&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Faith's Fetters",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485340&type=card",
        cmc: "4",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Falconer Adept",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485341&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Feat of Resistance",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485342&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Feline Sovereign",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485503&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Fetid Imp",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485421&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Fierce Empath",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485504&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Fiery Emancipation",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485466&type=card",
        cmc: "6",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Finishing Blow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485422&type=card",
        cmc: "5",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Forest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488474&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Forgotten Sentinel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485554&type=card",
        cmc: "4",
        color: "4",
        type: "Artifact",
    },
    {
        name: "Frantic Inventory",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485373&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Frost Breath",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485374&type=card",
        cmc: "3",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Fungal Rebirth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485505&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Furious Rise",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485467&type=card",
        cmc: "3",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Furor of the Bitten",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485468&type=card",
        cmc: "1",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Gadrak, the Crown-Scourge",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485469&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Gale Swooper",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485343&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Garruk, Savage Herald",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488642&type=card",
        cmc: "6",
        color: "Green",
        type: "Planeswalker",
    },
    {
        name: "Garruk, Unleashed",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485506&type=card",
        cmc: "4",
        color: "Green",
        type: "Planeswalker",
    },
    {
        name: "Garruk's Gorehorn",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485507&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Garruk's Harbinger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485508&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Garruk's Uprising",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485509&type=card",
        cmc: "3",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Garruk's Warsteed",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488643&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Ghostly Pilferer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485375&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Gloom Sower",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485423&type=card",
        cmc: "7",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Glorious Anthem",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485344&type=card",
        cmc: "3",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Gnarled Sage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485510&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Goblin Arsonist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485470&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Goblin Wizardry",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485471&type=card",
        cmc: "4",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Goremand",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485424&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Grasp of Darkness",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485425&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Griffin Aerie",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485345&type=card",
        cmc: "2",
        color: "White",
        type: "Enchantment",
    },
];

const core2021_page2 = [
    {
        name: "Grim Tutor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485426&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Havoc Jester",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485472&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Heartfire Immolator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485473&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Hellkite Punisher",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485474&type=card",
        cmc: "7",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Heroic Intervention",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485511&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Historian of Zhalfir",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488631&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Hobblefiend",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485475&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Hooded Blightfang",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485427&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Hunter's Edge",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485512&type=card",
        cmc: "4",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Idol of Endurance",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485346&type=card",
        cmc: "3",
        color: "White",
        type: "Artifact",
    },
    {
        name: "Igneous Cur",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485476&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Indulging Patrician",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485542&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Infernal Scarring",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485428&type=card",
        cmc: "2",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Invigorating Surge",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485513&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Island",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488465&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Jeskai Elder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485376&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Jolrael, Mwonvuli Recluse",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485514&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Jungle Hollow",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485570&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Kaervek, the Spiteful",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485429&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Keen Glidemaster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485377&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Keral Keep Disciples",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488640&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Kinetic Augur",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485477&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Kitesail Freebooter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485430&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Leafkin Avenger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485543&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Legion's Judgment",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485347&type=card",
        cmc: "3",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Library Larcenist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485378&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Life Goes On",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485515&type=card",
        cmc: "1",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Light of Promise",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485348&type=card",
        cmc: "3",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Liliana, Death Mage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488634&type=card",
        cmc: "6",
        color: "Black",
        type: "Planeswalker",
    },
    {
        name: "Liliana, Waker of the Dead",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485431&type=card",
        cmc: "4",
        color: "Black",
        type: "Planeswalker",
    },
    {
        name: "Liliana's Devotee",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485432&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Liliana's Scorn",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488635&type=card",
        cmc: "5",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Liliana's Scrounger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488636&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Liliana's Standard Bearer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485433&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Liliana's Steward",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485434&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Llanowar Visionary",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485516&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Lofty Denial",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485379&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Lorescale Coatl",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485544&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Makeshift Battalion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485349&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Malefic Scythe",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485435&type=card",
        cmc: "2",
        color: "Black",
        type: "Artifact",
    },
    {
        name: "Mangara, the Diplomat",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485350&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Masked Blackguard",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485436&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Massacre Wurm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485437&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Mazemind Tome",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485555&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Meteorite",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485556&type=card",
        cmc: "5",
        color: "5",
        type: "Artifact",
    },
    {
        name: "Mind Rot",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485438&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Miscast",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485380&type=card",
        cmc: "1",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Mistral Singer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485381&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Mountain",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488471&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Mystic Skyfish",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488632&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Necromentia",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485439&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Niambi, Esteemed Speaker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485545&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Nine Lives",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485351&type=card",
        cmc: "3",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Obsessive Stitcher",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485546&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Onakke Ogre",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485478&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Opt",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485382&type=card",
        cmc: "1",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Ornery Dilophosaur",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485517&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Pack Leader",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485352&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Palladium Myr",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485557&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Peer into the Abyss",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485440&type=card",
        cmc: "7",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Pestilent Haze",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485441&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Pitchburn Devils",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485479&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Plains",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488462&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Portcullis Vine",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485518&type=card",
        cmc: "1",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Predatory Wurm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488644&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Pridemalkin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485519&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Primal Might",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485520&type=card",
        cmc: "1",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Prismite",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485558&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Pursued Whale",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485383&type=card",
        cmc: "7",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Quirion Dryad",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485521&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Radha, Heart of Keld",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485547&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Radiant Fountain",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485571&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Rain of Revelation",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485384&type=card",
        cmc: "4",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Rambunctious Mutt",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485353&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Ranger's Guile",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485522&type=card",
        cmc: "1",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Read the Tides",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485385&type=card",
        cmc: "6",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Return to Nature",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485523&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Revitalize",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485354&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Rewind",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485386&type=card",
        cmc: "4",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Riddleform",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485387&type=card",
        cmc: "2",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Rin and Seri, Inseparable",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=489663&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Rise Again",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485442&type=card",
        cmc: "5",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Roaming Ghostlight",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485388&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Rookie Mistake",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485389&type=card",
        cmc: "1",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Rousing Read",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485390&type=card",
        cmc: "3",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Rugged Highlands",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485572&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Run Afoul",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485524&type=card",
        cmc: "1",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Runed Halo",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485355&type=card",
        cmc: "2",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Sabertooth Mauler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485525&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Sanctum of All",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485548&type=card",
        cmc: "5",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Sanctum of Calm Waters",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485391&type=card",
        cmc: "4",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Sanctum of Fruitful Harvest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485526&type=card",
        cmc: "3",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Sanctum of Shattered Heights",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485480&type=card",
        cmc: "3",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Sanctum of Stone Fangs",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485443&type=card",
        cmc: "2",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Sanctum of Tranquil Light",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485356&type=card",
        cmc: "1",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Sanguine Indulgence",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485444&type=card",
        cmc: "4",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Scavenging Ooze",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485527&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Scorching Dragonfire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485481&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Scoured Barrens",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485573&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Seasoned Hallowblade",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485357&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
];

const core2021_page3 = [
    {
        name: "Secure the Scene",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485358&type=card",
        cmc: "5",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "See the Truth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485392&type=card",
        cmc: "2",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Selfless Savior",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485359&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Setessan Training",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485528&type=card",
        cmc: "2",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Shacklegeist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485393&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Shipwreck Dowser",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485394&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Shock",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485482&type=card",
        cmc: "1",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Short Sword",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485559&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Siege Striker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485360&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Sigiled Contender",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488629&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Silent Dart",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485560&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Silversmote Ghoul",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485445&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Skeleton Archer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485446&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Skyscanner",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485561&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Skyway Sniper",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485529&type=card",
        cmc: "1",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Snarespinner",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485530&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Solemn Simulacrum",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485562&type=card",
        cmc: "4",
        color: "4",
        type: "Artifact",
    },
    {
        name: "Soul Sear",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485483&type=card",
        cmc: "3",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Sparkhunter Masticore",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485563&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Speaker of the Heavens",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485361&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Spellgorger Weird",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485484&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Spined Megalodon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485395&type=card",
        cmc: "7",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Spirit of Malevolence",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488637&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Sporeweb Weaver",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485531&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Staunch Shieldmate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485362&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Storm Caller",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488641&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Stormwing Entity",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485396&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Subira, Tulzidi Caravanner",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485485&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Sublime Epiphany",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485397&type=card",
        cmc: "6",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Sure Strike",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485486&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Swamp",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488468&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Swift Response",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485363&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Swiftwater Cliffs",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485574&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Tavern Swindler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485447&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Teferi, Master of Time",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488906&type=card",
        cmc: "4",
        color: "Blue",
        type: "Planeswalker",
    },
    {
        name: "Teferi, Timeless Voyager",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488630&type=card",
        cmc: "6",
        color: "Blue",
        type: "Planeswalker",
    },
    {
        name: "Teferi's Ageless Insight",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485399&type=card",
        cmc: "4",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Teferi's Protege",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485400&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Teferi's Tutelage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485401&type=card",
        cmc: "3",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Teferi's Wavecaster",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488633&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Tempered Veteran",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485364&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Temple of Epiphany",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485575&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Temple of Malady",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485576&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Temple of Mystery",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485577&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Temple of Silence",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485578&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Temple of Triumph",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485579&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Terror of the Peaks",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485487&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Thieves' Guild Enforcer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485448&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Thornwood Falls",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485580&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Thrashing Brontodon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485532&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Thrill of Possibility",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485488&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Tide Skimmer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485402&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Titanic Growth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485533&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Tolarian Kraken",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485403&type=card",
        cmc: "6",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Tome Anima",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485404&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Tormod's Crypt",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485564&type=card",
        cmc: "0",
        color: "0",
        type: "Artifact",
    },
    {
        name: "Track Down",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485534&type=card",
        cmc: "2",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Traitorous Greed",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485489&type=card",
        cmc: "4",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Tranquil Cove",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485581&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Transmogrify",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485490&type=card",
        cmc: "4",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Trufflesnout",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485535&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Turn to Slag",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485491&type=card",
        cmc: "5",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Turret Ogre",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485492&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Twinblade Assassins",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485549&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Ugin, the Spirit Dragon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485324&type=card",
        cmc: "8",
        color: "8",
        type: "Planeswalker",
    },
    {
        name: "Unleash Fury",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485493&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Unsubstantiate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485405&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Valorous Steed",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485365&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Village Rites",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485449&type=card",
        cmc: "1",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Vito, Thorn of the Dusk Rose",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485450&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Vodalian Arcanist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485406&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Volcanic Geyser",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485494&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Volcanic Salvo",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485495&type=card",
        cmc: "12",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Vryn Wingmare",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485366&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Waker of Waves",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485407&type=card",
        cmc: "7",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Walking Corpse",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485451&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Wall of Runes",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485408&type=card",
        cmc: "1",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Warded Battlements",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485367&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Warden of the Woods",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485536&type=card",
        cmc: "6",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Watcher of the Spheres",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485550&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Wildwood Patrol",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=488645&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Wildwood Scourge",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485537&type=card",
        cmc: "1",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Wind-Scarred Crag",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485582&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Wishcoin Crab",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485409&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Witch's Cauldron",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485452&type=card",
        cmc: "1",
        color: "Black",
        type: "Artifact",
    },
];

export const core2021 = core2021_page1.concat(core2021_page2, core2021_page3);
export const core2021Obj = core2021.reduce((acc, card) => {
    return {
        ...acc,
        [card.name]: {
            ["image"]: card.image,
            ["cmc"]: card.cmc,
            ["color"]: card.color,
            ["type"]: card.type,
        },
    };
}, {});
