export const masters25_page1 = [
    {
        name: "Accumulated Knowledge",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442029&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Act of Heroism",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=441990&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Act of Treason",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442107&type=card",
        cmc: "3",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Ainok Survivalist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442146&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Akroma, Angel of Fury",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442108&type=card",
        cmc: "8",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Akroma, Angel of Wrath",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=441991&type=card",
        cmc: "8",
        color: "White",
        type: "Creature",
    },
    {
        name: "Akroma's Vengeance",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=441992&type=card",
        cmc: "6",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Ambassador Oak",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442147&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Ancient Craving",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442068&type=card",
        cmc: "4",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Ancient Stirrings",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442148&type=card",
        cmc: "1",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Angelic Page",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=441993&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Animar, Soul of Elements",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442185&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Arbor Elf",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442149&type=card",
        cmc: "1",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Arcane Denial",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442030&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Armageddon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=441994&type=card",
        cmc: "4",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Ash Barrens",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442225&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Assembly-Worker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442210&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Auramancer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=441995&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Azusa, Lost but Seeking",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442150&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Balduvian Horde",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442109&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Ball Lightning",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442110&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Baloth Null",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442186&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Bident of Thassa",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442031&type=card",
        cmc: "4",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Blightning",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442187&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Blood Moon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442111&type=card",
        cmc: "3",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Bloodhunter Bat",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442069&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Blue Elemental Blast",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442032&type=card",
        cmc: "1",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Blue Sun's Zenith",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442033&type=card",
        cmc: "3",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Boros Charm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442188&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Borrowing 100,000 Arrows",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442034&type=card",
        cmc: "3",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Brainstorm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442035&type=card",
        cmc: "1",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Brine Elemental",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442036&type=card",
        cmc: "6",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Brion Stoutarm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442189&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Broodhatch Nantuko",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442151&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Browbeat",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442112&type=card",
        cmc: "3",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Cascade Bluffs",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442226&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Caustic Tar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442070&type=card",
        cmc: "6",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Chalice of the Void",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442211&type=card",
        cmc: "0",
        color: "Variable Colorless",
        type: "Artifact",
    },
    {
        name: "Chandra's Outrage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442113&type=card",
        cmc: "4",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Chartooth Cougar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442114&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Choking Tethers",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442037&type=card",
        cmc: "4",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Cinder Storm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442115&type=card",
        cmc: "7",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Cloudblazer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442190&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Cloudshift",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=441996&type=card",
        cmc: "1",
        color: "White",
        type: "Instant",
    },
    {
        name: "Coalition Relic",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442212&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Colossal Dreadmaw",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442152&type=card",
        cmc: "6",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Conflux",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442191&type=card",
        cmc: "8",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Congregate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=441997&type=card",
        cmc: "4",
        color: "White",
        type: "Instant",
    },
    {
        name: "Coralhelm Guide",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442038&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Counterspell",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442039&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Courser of Kruphix",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442153&type=card",
        cmc: "3",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Court Hussar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442040&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Crimson Mage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442116&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Cultivate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442154&type=card",
        cmc: "3",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Curiosity",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442041&type=card",
        cmc: "1",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Cursecatcher",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442042&type=card",
        cmc: "1",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Darien, King of Kjeldor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=441998&type=card",
        cmc: "6",
        color: "White",
        type: "Creature",
    },
    {
        name: "Dark Ritual",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442071&type=card",
        cmc: "1",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Dauntless Cathar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=441999&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Deadly Designs",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442072&type=card",
        cmc: "2",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Death's-Head Buzzard",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442073&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Decree of Justice",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442000&type=card",
        cmc: "4",
        color: "Variable Colorless",
        type: "Sorcery",
    },
    {
        name: "Diabolic Edict",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442074&type=card",
        cmc: "2",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Dirge of Dread",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442075&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Disenchant",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442001&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Disfigure",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442076&type=card",
        cmc: "1",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Doomsday",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442077&type=card",
        cmc: "3",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Dragon's Eye Savants",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442043&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Dusk Legion Zealot",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442078&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Echoing Courage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442155&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Eidolon of the Great Revel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442117&type=card",
        cmc: "2",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Eladamri's Call",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442192&type=card",
        cmc: "2",
        color: "White",
        type: "Instant",
    },
    {
        name: "Elvish Aberration",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442156&type=card",
        cmc: "6",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Elvish Piper",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442157&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Ember Weaver",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442158&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Ensnaring Bridge",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442213&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Enthralling Victor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442118&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Epic Confrontation",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442159&type=card",
        cmc: "2",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Erg Raiders",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442079&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Exclude",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442044&type=card",
        cmc: "3",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Fallen Angel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442080&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Fathom Seer",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442045&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Fencing Ace",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442002&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Fetid Heath",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442227&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Fiend Hunter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442003&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Fierce Empath",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442160&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Flash",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442046&type=card",
        cmc: "2",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Flooded Grove",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442228&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Fortune Thief",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442119&type=card",
        cmc: "5",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Freed from the Real",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442047&type=card",
        cmc: "3",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Frenzied Goblin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442120&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Geist of the Moors",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442004&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Genju of the Falls",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442048&type=card",
        cmc: "1",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Genju of the Spires",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442121&type=card",
        cmc: "1",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Ghost Ship",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442049&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Giant Growth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442161&type=card",
        cmc: "1",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Gisela, Blade of Goldnight",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442193&type=card",
        cmc: "7",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Goblin War Drums",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442122&type=card",
        cmc: "3",
        color: "Red",
        type: "Enchantment",
    },
    {
        name: "Gods Willing",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442005&type=card",
        cmc: "1",
        color: "White",
        type: "Instant",
    },
    {
        name: "Grenzo, Dungeon Warden",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442194&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
];
const masters25_page2 = [
    {
        name: "Griffin Protector",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442006&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Hanna, Ship's Navigator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442195&type=card",
        cmc: "3",
        color: "White",
        type: "Creature",
    },
    {
        name: "Haunted Fengraf",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442229&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Heavy Arbalest",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442214&type=card",
        cmc: "3",
        color: "3",
        type: "Artifact",
    },
    {
        name: "Hell's Caretaker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442081&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Hordeling Outburst",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442123&type=card",
        cmc: "3",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Horror of the Broken Lands",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442082&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Horseshoe Crab",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442050&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Humble Defector",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442124&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Ihsan's Shade",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442083&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Imperial Recruiter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442125&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Invigorate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442162&type=card",
        cmc: "3",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Ire Shaman",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442126&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Iwamori of the Open Fist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442163&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Izzet Chemister",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442127&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Jace, the Mind Sculptor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442051&type=card",
        cmc: "4",
        color: "Blue",
        type: "Planeswalker",
    },
    {
        name: "Jackal Pup",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442128&type=card",
        cmc: "1",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Jalira, Master Polymorphist",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442052&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Karona's Zealot",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442007&type=card",
        cmc: "5",
        color: "White",
        type: "Creature",
    },
    {
        name: "Kavu Climber",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442164&type=card",
        cmc: "5",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Kavu Predator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442165&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Kindle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442129&type=card",
        cmc: "2",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Knight of the Skyward Eye",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442008&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: 'Kongming, "Sleeping Dragon"',
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442009&type=card",
        cmc: "4",
        color: "White",
        type: "Creature",
    },
    {
        name: "Kor Firewalker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442010&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Krosan Colossus",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442166&type=card",
        cmc: "9",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Krosan Tusker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442167&type=card",
        cmc: "7",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Laquatus's Champion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442084&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Lightning Bolt",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442130&type=card",
        cmc: "1",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Living Death",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442085&type=card",
        cmc: "5",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Living Wish",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442168&type=card",
        cmc: "2",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Lorescale Coatl",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442196&type=card",
        cmc: "3",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Loyal Sentry",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442011&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Lull",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442169&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Luminarch Ascension",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442012&type=card",
        cmc: "2",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Lunarch Mantle",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442013&type=card",
        cmc: "2",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Magus of the Wheel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442131&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Man-o'-War",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442053&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Master of the Wild Hunt",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442170&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Merfolk Looter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442054&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Mesmeric Fiend",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442086&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Mikokoro, Center of the Sea",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442230&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Mishra's Factory",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442231&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Mogg Flunkies",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442132&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Murder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442087&type=card",
        cmc: "3",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Murder of Crows",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442055&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Myriad Landscape",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442232&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Mystic of the Hidden Way",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442056&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Mystic Snake",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442197&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Nettle Sentinel",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442171&type=card",
        cmc: "1",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Nezumi Cutthroat",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442088&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Nicol Bolas",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442198&type=card",
        cmc: "8",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Nihil Spellbomb",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442215&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Niv-Mizzet, the Firemind",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442199&type=card",
        cmc: "6",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Noble Templar",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442014&type=card",
        cmc: "6",
        color: "White",
        type: "Creature",
    },
    {
        name: "Notion Thief",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442200&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Nyx-Fleece Ram",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442015&type=card",
        cmc: "2",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Ordeal of Heliod",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442016&type=card",
        cmc: "2",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Pacifism",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442017&type=card",
        cmc: "2",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Pact of Negation",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442057&type=card",
        cmc: "0",
        color: "0",
        type: "Instant",
    },
    {
        name: "Path of Peace",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442018&type=card",
        cmc: "4",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Pendelhaven",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442233&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Perilous Myr",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442216&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Pernicious Deed",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442201&type=card",
        cmc: "3",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Phantasmal Bear",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442058&type=card",
        cmc: "1",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Phyrexian Ghoul",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442089&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Phyrexian Obliterator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442090&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Pillage",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442133&type=card",
        cmc: "3",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Pillory of the Sleepless",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442202&type=card",
        cmc: "3",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Plague Wind",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442091&type=card",
        cmc: "9",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Plummet",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442172&type=card",
        cmc: "2",
        color: "Green",
        type: "Instant",
    },
    {
        name: "Presence of Gond",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442173&type=card",
        cmc: "3",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Primal Clay",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442217&type=card",
        cmc: "4",
        color: "4",
        type: "Artifact",
    },
    {
        name: "Promise of Bunrei",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442019&type=card",
        cmc: "3",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Prophetic Prism",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442218&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Prossh, Skyraider of Kher",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442203&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Protean Hulk",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442174&type=card",
        cmc: "7",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Pyre Hound",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442134&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Pyroclasm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442135&type=card",
        cmc: "2",
        color: "Red",
        type: "Sorcery",
    },
    {
        name: "Quicksand",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442234&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Quicksilver Dagger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442204&type=card",
        cmc: "3",
        color: "Blue",
        type: "Enchantment",
    },
    {
        name: "Rancor",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442175&type=card",
        cmc: "1",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Ratcatcher",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442092&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Ravenous Chupacabra",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442093&type=card",
        cmc: "4",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Red Elemental Blast",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442136&type=card",
        cmc: "1",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Reef Worm",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442059&type=card",
        cmc: "4",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Regrowth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442176&type=card",
        cmc: "2",
        color: "Green",
        type: "Sorcery",
    },
    {
        name: "Relentless Rats",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442094&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Renewed Faith",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442020&type=card",
        cmc: "3",
        color: "White",
        type: "Instant",
    },
    {
        name: "Rest in Peace",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442021&type=card",
        cmc: "2",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Retraction Helix",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442060&type=card",
        cmc: "1",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Returned Phalanx",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442095&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Rishadan Port",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442235&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Rugged Prairie",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442236&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Ruric Thar, the Unbowed",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442205&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Ruthless Ripper",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442096&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Sai of the Shinobi",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442219&type=card",
        cmc: "1",
        color: "1",
        type: "Artifact",
    },
    {
        name: "Savannah Lions",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442022&type=card",
        cmc: "1",
        color: "White",
        type: "Creature",
    },
    {
        name: "Self-Assembler",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442220&type=card",
        cmc: "5",
        color: "5",
        type: "Artifact",
    },
    {
        name: "Shadowmage Infiltrator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442206&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
];
const masters25_page3 = [
    {
        name: "Shoreline Ranger",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442061&type=card",
        cmc: "6",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Sift",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442062&type=card",
        cmc: "4",
        color: "Blue",
        type: "Sorcery",
    },
    {
        name: "Simian Spirit Guide",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442137&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Skeletonize",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442138&type=card",
        cmc: "5",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Skirk Commando",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442139&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Soulbright Flamekin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442140&type=card",
        cmc: "2",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Spikeshot Goblin",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442141&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Squadron Hawk",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442023&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Stampede Driver",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442177&type=card",
        cmc: "1",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Stangg",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442207&type=card",
        cmc: "6",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Street Wraith",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442097&type=card",
        cmc: "5",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Strionic Resonator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442221&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Summoner's Pact",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442178&type=card",
        cmc: "0",
        color: "0",
        type: "Instant",
    },
    {
        name: "Sundering Titan",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442222&type=card",
        cmc: "8",
        color: "8",
        type: "Artifact",
    },
    {
        name: "Supernatural Stamina",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442098&type=card",
        cmc: "1",
        color: "Black",
        type: "Instant",
    },
    {
        name: "Swiftfoot Boots",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442223&type=card",
        cmc: "2",
        color: "2",
        type: "Artifact",
    },
    {
        name: "Swords to Plowshares",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442024&type=card",
        cmc: "1",
        color: "White",
        type: "Instant",
    },
    {
        name: "Thalia, Guardian of Thraben",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442025&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Thresher Lizard",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442142&type=card",
        cmc: "3",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Timberpack Wolf",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442179&type=card",
        cmc: "2",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Totally Lost",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442063&type=card",
        cmc: "5",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Treasure Keeper",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442224&type=card",
        cmc: "4",
        color: "4",
        type: "Artifact",
    },
    {
        name: "Tree of Redemption",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442180&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Triskaidekaphobia",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442099&type=card",
        cmc: "4",
        color: "Black",
        type: "Enchantment",
    },
    {
        name: "Trumpet Blast",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442143&type=card",
        cmc: "3",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Twilight Mire",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442237&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Twisted Abomination",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442100&type=card",
        cmc: "6",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Twisted Image",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442064&type=card",
        cmc: "1",
        color: "Blue",
        type: "Instant",
    },
    {
        name: "Uncaged Fury",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442144&type=card",
        cmc: "3",
        color: "Red",
        type: "Instant",
    },
    {
        name: "Undead Gladiator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442101&type=card",
        cmc: "3",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Unearth",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442102&type=card",
        cmc: "1",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Urbis Protector",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442026&type=card",
        cmc: "6",
        color: "White",
        type: "Creature",
    },
    {
        name: "Utopia Sprawl",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442181&type=card",
        cmc: "1",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Valor in Akros",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442027&type=card",
        cmc: "4",
        color: "White",
        type: "Enchantment",
    },
    {
        name: "Vampire Lacerator",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442103&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Vendilion Clique",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442065&type=card",
        cmc: "3",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Vessel of Nascency",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442182&type=card",
        cmc: "1",
        color: "Green",
        type: "Enchantment",
    },
    {
        name: "Vesuvan Shapeshifter",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442066&type=card",
        cmc: "5",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Vindicate",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442208&type=card",
        cmc: "3",
        color: "White",
        type: "Sorcery",
    },
    {
        name: "Watchwolf",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442209&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Whitemane Lion",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442028&type=card",
        cmc: "2",
        color: "White",
        type: "Creature",
    },
    {
        name: "Wildheart Invoker",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442183&type=card",
        cmc: "4",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Willbender",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442067&type=card",
        cmc: "2",
        color: "Blue",
        type: "Creature",
    },
    {
        name: "Will-o'-the-Wisp",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442104&type=card",
        cmc: "1",
        color: "Black",
        type: "Creature",
    },
    {
        name: "Woolly Loxodon",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442184&type=card",
        cmc: "7",
        color: "Green",
        type: "Creature",
    },
    {
        name: "Zada, Hedron Grinder",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442145&type=card",
        cmc: "4",
        color: "Red",
        type: "Creature",
    },
    {
        name: "Zoetic Cavern",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442238&type=card",
        cmc: "0",
        color: undefined,
        type: "Land",
    },
    {
        name: "Zombify",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442105&type=card",
        cmc: "4",
        color: "Black",
        type: "Sorcery",
    },
    {
        name: "Zulaport Cutthroat",
        image: "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=442106&type=card",
        cmc: "2",
        color: "Black",
        type: "Creature",
    },
];

export const masters25 = masters25_page1.concat(masters25_page2, masters25_page3);

export const masters25Obj = masters25.reduce((acc, card) => {
    return {
        ...acc,
        [card.name]: {
            ["image"]: card.image,
            ["cmc"]: card.cmc,
            ["color"]: card.color,
            ["type"]: card.type,
        },
    };
}, {});
